- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
- packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
- packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
> Fixed relative paths to node_modules

- packages/ckeditor5-dev-utils/lib/git.js
- packages/ckeditor5-dev-utils/tests/git.js
> Regexp for parsing repository URL matches also the tag.

- packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
- packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
- packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
- packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js
- packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
> Change paths to source files

- packages/ckeditor5-dev-env/tests/release-tools/tasks/createrelease.js
> Tests: Add test scenario for #63.

- packages/jsdoc-plugins/lib/utils/doclet-logger.js
Fixes this: https://github.com/ckeditor/ckeditor5-dev/issues/82
> Changed parseComplete event to processingComplete event. Fixes #82.

- packages/jsdoc-plugins/lib/validator/doclet-validator.js
- packages/jsdoc-plugins/tests/doclet-validator.js
Fixes https://github.com/ckeditor/ckeditor5-dev/issues/89.
> Fixed problem with NullLiteral and UndefinedLiteral type params

- packages/ckeditor5-dev-env/lib/translations/download.js
- packages/ckeditor5-dev-env/lib/translations/languagecodemap.json
- packages/ckeditor5-dev-env/package.json
- packages/ckeditor5-dev-env/tests/translations/download.js
- packages/ckeditor5-dev-utils/lib/translations/index.js
> Add language code mapping and old translations removing, prevent empty po files saving

- packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelog.js
- packages/ckeditor5-dev-env/tests/release-tools/tasks/generatechangelog.js
Fix: Changelog task will not trigger a CI. Closes #98.
> T/98: Changelog should be committed with [skip ci]

- packages/ckeditor5-dev-env/lib/release-tools/changelog/writer-options.js
- packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelog.js
- packages/ckeditor5-dev-env/lib/release-tools/utils/cli.js
- packages/ckeditor5-dev-env/lib/release-tools/utils/getnewreleasetype.js
- packages/ckeditor5-dev-env/tests/release-tools/changelog/transformcommit.js
- packages/ckeditor5-dev-env/tests/release-tools/tasks/generatechangelog.js
- packages/ckeditor5-dev-env/tests/release-tools/utils/cli.js
Fix: Recommended version was incorrect for merge commits. Closes #97.
> T/97: Breaking changes and new feature were ignored

- packages/ckeditor5-dev-env/lib/release-tools/changelog/writer-options.js
- packages/ckeditor5-dev-env/tests/release-tools/changelog/transformcommit.js
- packages/ckeditor5-dev-env/tests/release-tools/utils/getnewreleasetype.js
Fix: Changelog contained invalid URLs to Github issues. Closes #104.
> T/104: Fixed invalid URLs to Github issues.

- packages/ckeditor5-dev-tests/bin/save-revision.js
Internal: "mgit.json" will be always taken from the main branch.
Missing part for the previous PR (#54). Now `mgit.json` always will be taken from `origin/master`.
> Tool for saving history state from CKE5 deps (2)

- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
- packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js
Internal: Added showDiff to Mocha reporter. Closes #133.
> T/133 Add showDiff to Mocha reporter

- packages/ckeditor5-dev-env/tests/translations/collect-utils.js
- packages/ckeditor5-dev-env/tests/translations/collect.js
- packages/ckeditor5-dev-env/tests/translations/download.js
- packages/ckeditor5-dev-env/tests/translations/transifex-service.js
- packages/ckeditor5-dev-env/tests/translations/upload.js
- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
- packages/ckeditor5-dev-utils/lib/translations/findoriginalstrings.js
- packages/ckeditor5-dev-utils/tests/translations/findoriginalstrings.js
TODO: Two files still miss 100% CC.
> Add more tests for the translation scripts.

- packages/ckeditor5-dev-env/lib/release-tools/utils/cli.js
- packages/ckeditor5-dev-env/tests/release-tools/utils/cli.js
Fix: Versions of packages to release were shown inconsistently. Closes #100.
> T/100: Release task shows versions inconsistently

- packages/ckeditor5-dev-tests/package.json
> T/155 Update webpack

- packages/ckeditor5-dev-env/lib/release-tools/utils/cli.js
- packages/ckeditor5-dev-env/tests/release-tools/utils/cli.js
Fix: Packages to release will be ordered by alphabetical. Closes #150.
> T/150: The packages to release are not sorted alphabetically

- .vscode/settings.json
- packages/ckeditor5-dev-env/lib/translations/transifex-service.js
- packages/ckeditor5-dev-env/lib/translations/upload.js
- packages/ckeditor5-dev-env/tests/translations/transifex-service.js
- packages/ckeditor5-dev-env/tests/translations/upload.js
> T/174 Fix translations upload to transifex

- packages/ckeditor5-dev-env/lib/release-tools/templates/commit.hbs
- packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/parser-options.js
- packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transform-commit-utils.js
- packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubrepository.js
- packages/ckeditor5-dev-env/tests/release-tools/templates/commit.js
- packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits-integration.js
- packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/parseroptions.js
- packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transform-commit-utils.js
- packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubrepository.js
Fix: Closed ticket should not be hoisted. Closes #161.
> T/161: Closed tickets should not be hoisted

- packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits-integration.js
Internal: Hide logs during the tests execution. Closes #194.
---
Marked as `Internal` because this test was added in the current release.
> T/194: `generateChangelogFromCommits()` logs into the console during the tests

- packages/jsdoc-plugins/README.md
Docs: Updated JSDoc plugins documentation. Closes #210 .
> Updated JSDoc plugins readme.

- packages/ckeditor5-dev-docs/lib/index.js
- packages/jsdoc-plugins/lib/validator/validator.js
Feature: Allows breaking the process if validation does not pass. Closes #221.
> T/221: Allows validating the API Docs only

- packages/ckeditor5-dev-env/README.md
Internal: Improved the README. Closes #111.
> T/111: Ckeditor5-dev-env has invalid README

- packages/ckeditor5-dev-docs/lib/index.js
- packages/jsdoc-plugins/lib/custom-tags/error.js
- packages/jsdoc-plugins/lib/longname-fixer/fixers/fix-links.js
- packages/jsdoc-plugins/lib/utils/doclet-utils.js
- packages/jsdoc-plugins/tests/doclet-validator.js
- packages/jsdoc-plugins/tests/fix-links.js
Feature: Provided `@error` tag detection in JSDoc. Closes #280.
> Provide error tag detection.

- packages/ckeditor5-dev-tests/bin/check-dependencies.js
Fix: Dependency Checker - non-relative links to itself will be caught. Closes #282.
> T/282: Dependency Checker (imports from itself)

- packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
- packages/ckeditor5-dev-tests/package.json
- packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js
Feature: Changed a way how the tests are executed. Karma will receive a single entry point which will import all tests. Closes #290.
> T/290: Tests are executed as a single entry point

- packages/jsdoc-plugins/lib/relation-fixer/addmissingdoclets.js
- packages/jsdoc-plugins/lib/relation-fixer/buildrelations.js
- packages/jsdoc-plugins/lib/relation-fixer/getmissingdocletsdata.js
- packages/jsdoc-plugins/lib/utils/doclet-collection.js
- packages/jsdoc-plugins/tests/doclet-collection.js
Fix: Optimized Relation Fixer plugin. Closes #312.
---
Used DocletCollection to reduce the number of operations on arrays of doclets.
> T/312: Optimized Relation Fixer plugin

- packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
- packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilescripts.js
- packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js
- packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilescripts.js
Fix: Manual tests will work in Windows environments properly. Closes: #325.
> T/325: MT will work on Windows

- packages/jsdoc-plugins/lib/validator/doclet-validator.js
- packages/jsdoc-plugins/tests/doclet-validator.js
Fix: Improved linting `memberof` property. Closes ckeditor/ckeditor5-utils#209.
> [JSDoc] Improve linting `memberof` property

- packages/ckeditor5-dev-utils/lib/translations/multiplelanguagetranslationservice.js
- packages/ckeditor5-dev-utils/tests/translations/multiplelanguagetranslationservice.js
- packages/ckeditor5-dev-webpack-plugin/lib/index.js
- packages/ckeditor5-dev-webpack-plugin/lib/servetranslations.js
- packages/ckeditor5-dev-webpack-plugin/package.json
- packages/ckeditor5-dev-webpack-plugin/tests/index.js
Fix: Added language directory cleaning before each webpack build. Closes ckeditor/ckeditor5#700.
> Add language directory cleaning before each webpack build

- packages/ckeditor5-dev-utils/package.json
Other: Reverted original escodegen package. Closes #337.
> Revert original escodegen package

- packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
- packages/ckeditor5-dev-tests/tests/tasks/runautomatedtests.js
Fix: Karma will not execute the tests multiple times when works in watch mode. Closes #346.
> T/346: Karma / Webpack watcher

- packages/jsdoc-plugins/lib/validator/doclet-validator.js
- packages/jsdoc-plugins/tests/doclet-validator.js
Fix: Improved links detection and validation. Closes #365.
> Improve links detection and validation

- packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js
Tests: Fixed failing test on Travis caused by the forked repository. Closes #383.
> Fixed failing test on Travis caused by the forked repository

- packages/ckeditor5-dev-env/lib/translations/collect-utils.js
- packages/ckeditor5-dev-env/tests/translations/collect-utils.js
Internal: Allowed reusing other packages' translations. Hotfix for #413.
> Allow reusing other packages' translations

- packages/ckeditor5-dev-tests/lib/utils/manual-tests/createserver.js
- packages/ckeditor5-dev-tests/lib/utils/manual-tests/template.html
Feature: Grouped manual tests in the list. Slightly redesigned the manual test index. Closes #422.
> t/422: Grouped manual tests in the list

- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
Internal: Removed unnecessary logs from the `npm t` command. Closes #418.
> Remove unnecessary logs from the `npm t` command

- packages/ckeditor5-dev-docs/package.json
- packages/ckeditor5-dev-env/package.json
- packages/ckeditor5-dev-tests/package.json
- packages/ckeditor5-dev-utils/package.json
- packages/ckeditor5-dev-webpack-plugin/package.json
- packages/jsdoc-plugins/package.json
Internal: Disabled publishing tests which aren't required on npm.
> Added "files" section for each package.json

- packages/jsdoc-plugins/lib/relation-fixer/getmissingdocletsdata.js
Internal: Speeded up JSDoc plugin that fixes inheritance. Closes #438.
---
From:
```
JSDoc started...
No errors found during the validation.
Documented 396 files!
173.51 real       167.94 user         1.87 sys
```
to:
```
JSDoc started...
No errors found during the validation.
Documented 396 files!
18.79 real        19.01 user         1.16 sys
```
I don't think any further optimizations will be necessary.
> Speed up JSDoc plugin that fixes inheritance

- packages/ckeditor5-dev-tests/package.json
Other: Update raw-loader dependency.
---
* part of: https://github.com/ckeditor/ckeditor5/pull/1422
> Update raw-loader dependency.

- packages/ckeditor5-dev-tests/bin/add-workspace-to-package-json.js
- packages/ckeditor5-dev-tests/bin/install-dependencies.sh
Fix: The main repository should be added to yarn workspaces. Closes ckeditor/ckeditor5-paragraph#39.
---
* Happy testing.
* Requires changes in mgit2: https://github.com/cksource/mgit2/pull/97
> Add root package to package.json workspaces.

- packages/ckeditor5-dev-utils/lib/translations/cleanpofilecontent.js
- packages/ckeditor5-dev-utils/tests/translations/cleanpofilecontent.js
Internal: Added special headers to downloaded translation files from Tx. Closes #478.
---
> Add special headers to downloaded translation files from Tx

- packages/ckeditor5-dev-tests/bin/check-dependencies.js
- packages/ckeditor5-dev-tests/package.json
Feature: Improved script which checks dependencies on CI. Added two new informations – which dependencies and devDependencies are unused in the package. The entire script response is now displayed in the table. Closes #392.
> Upgraded script which checks dependencies

- packages/ckeditor5-dev-tests/bin/check-dependencies.js
- packages/ckeditor5-dev-tests/bin/test-travis.sh
- packages/ckeditor5-dev-tests/bin/test.js
- packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
Fix: Fixed issues related to a new dependency checker on Travis. Closes ckeditor/ckeditor5#1662.
> Fixes errors on Travis

- packages/ckeditor5-dev-tests/bin/check-dependencies.js
- packages/ckeditor5-dev-tests/package.json
Fix: List with dependency issues will be displayed in a more readable way. Closes #512.
---
> Dependency Issues will be displayed in a more readable way

- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
Other: Upgraded a version of Safari. Closes #517.
> Upgraded a version of Safari

- packages/jsdoc-plugins/lib/doclet.jsdoc
- packages/jsdoc-plugins/lib/relation-fixer/addmissingdoclets.js
- packages/jsdoc-plugins/lib/relation-fixer/addtypedefproperties.js
- packages/jsdoc-plugins/lib/relation-fixer/getmissingdocletsdata.js
- packages/jsdoc-plugins/lib/relation-fixer/index.js
- packages/jsdoc-plugins/tests/relation-fixer/relationfixerintegration.js
Other: Enabled doclets generation out of typedef properties. Closes #504.
---
> [WIP] Enabled doclets generation out of typedef properties

- packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js
Fix: Adjusted usage of GitHub API to the latest version. All API's methods return an instance of `Promise` instead of requiring a callback as the last parameter.  Closes ckeditor/ckeditor5#1889.
> Adjusted usage of GitHub API to the latest version

- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
Feature: Enabled automated test remote debugging in Chrome (Karma). Closes #544.
> t/544: Enabled automated test remote debugging in Chrome

- packages/ckeditor5-dev-utils/lib/translations/findoriginalstrings.js
- packages/ckeditor5-dev-utils/lib/translations/translatesource.js
- packages/ckeditor5-dev-utils/package.json
Internal: Update acorn dependency.
---
> Update acorn dependency.

- packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
- packages/ckeditor5-dev-tests/tests/tasks/runautomatedtests.js
Internal: Fixed console patching. Closes #566.
---
> Fix console patching

- yarn.lock
Internal: Updated dependencies in `yarn.lock`. See ckeditor/ckeditor5#5926.
> Deps upgrade

- packages/ckeditor5-dev-tests/README.md
- packages/ckeditor5-dev-tests/bin/intellijkarmarunner/README.md
- packages/ckeditor5-dev-tests/bin/intellijkarmarunner/bin/karma
- packages/ckeditor5-dev-tests/bin/intellijkarmarunner/karma.config.js
- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
- packages/ckeditor5-dev-tests/lib/utils/automated-tests/parsearguments.js
Feature: Added integration with Intellij IDEs. Closes #582.
> Integration with Intellij IDEs

- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
- packages/ckeditor5-dev-tests/package.json
Internal (tests): Removed automatic coveralls CC report uploading. Closes #635.
> Removed automatic coveralls reporting

- packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js
Fix (env): The `releaseSubRepositories()` task should not throw any error if publishing from the non-master branch. Closes ckeditor/ckeditor5#7300.
> Support for "releaseBranch" in "releaseSubRepositories()"

- .gitignore
- package.json
- yarn.lock
Internal: Replaced `istanbul` with `ncy`. Closes ckeditor/ckeditor5#7396.
> Replaced istanbul with ncy

- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
- packages/ckeditor5-dev-tests/package.json
- packages/ckeditor5-dev-tests/tests/tasks/runautomatedtests.js
- packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js
Feature (tests): Added `sinon-chai` to automated tests. Closes https://github.com/ckeditor/ckeditor5/issues/7456
---
It closes only first part. Docs are still to be covered in a separate PR.
> Add sinon-chai to the karma config.

- packages/ckeditor5-dev-tests/bin/check-dependencies.js
Feature (tests): Dependency checker will look for duplicated dependencies. Closes ckeditor/ckeditor5#7706.
---
After executing the script, I found duplicates in `table` and `widget` packages. PR – https://github.com/ckeditor/ckeditor5/pull/7748.
> Dependency checker will look for duplicated dependencies

- packages/ckeditor5-dev-docs/lib/index.js
- packages/jsdoc-plugins/lib/validator/validator.js
Feature (docs): Added support for the `--strict` flag while building documentation. See ckeditor/ckeditor5#7994.
> Added support for the "--strict" flag while building documentation

- packages/ckeditor5-dev-utils/lib/builds/getdllpluginwebpackconfig.js
Internal: Align webpack DLL plugin to the changes in the main repo. See ckeditor/ckeditor5#8609.
---
*   Requried for ckeditor/ckeditor5#8624
> Align webpack DLL plugin to the changes in main repo.

- packages/ckeditor5-dev-utils/lib/builds/getdllpluginwebpackconfig.js
Internal: Read DLL from the scoped variable. See ckeditor/ckeditor5#8575.
---
Should be merged together with https://github.com/ckeditor/ckeditor5/pull/8631.
> Read DLL from the scoped variable

- packages/jsdoc-plugins/lib/purge-private-api-docs.js
Internal: Improved building docs for private projects. Closes https://github.com/ckeditor/ckeditor5/issues/8751.
---
> Improved building docs for private projects.

- packages/jsdoc-plugins/lib/validator/types.js
Internal: Added new types for the doclet validator. Closes ckeditor/ckeditor5#8784.
---
> Added new types for the doclet validator.

- .travis.yml
Internal: Send a slack notification if CI failed for the `ckeditor5-dev` repository. Closes ckeditor/ckeditor5#8381.
> Send slack notification if CI failed for the ckeditor5-dev repository.

- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
- packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js
Other (tests): Added in the Karma configuration a list of available plugins to avoid an error related to loading a non-registered plugin.
---
Closes cksource/ckeditor5-internal#741.
---
> Fixed an issue with karma being not able to compile automated tests

- package.json
- packages/ckeditor5-dev-env/lib/translations/upload.js
- packages/ckeditor5-dev-env/tests/release-tools/utils/getchangedfilesforcommit.js
- packages/ckeditor5-dev-env/tests/release-tools/utils/getcommits.js
- packages/ckeditor5-dev-env/tests/translations/upload.js
- packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
- packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
- packages/ckeditor5-dev-tests/lib/utils/manual-tests/createserver.js
- packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js
- packages/ckeditor5-dev-tests/tests/utils/manual-tests/createserver.js
- packages/ckeditor5-dev-utils/lib/workspace.js
- packages/ckeditor5-dev-utils/tests/tools.js
- packages/ckeditor5-dev-utils/tests/workspace.js
- packages/jsdoc-plugins/tests/integration-tests/_utils/extract-api-docs.js
Tests: Fixed majority of tests on Windows. Closes ckeditor/ckeditor5#10388.
---
> Fixed majority of tests on Windows

- packages/ckeditor5-dev-env/lib/index.js
- packages/ckeditor5-dev-env/lib/release-tools/tasks/bump-year.js
- packages/ckeditor5-dev-env/tests/index.js
- scripts/bump-year.js
Feature (env): Created the script for bumping a year in license headers. Closes ckeditor/ckeditor5#10909.
> Created the script for bumping a year in license headers.

- packages/ckeditor5-dev-tests/bin/check-dependencies.js
- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
- packages/ckeditor5-dev-tests/lib/utils/transformfileoptiontotestglob.js
- packages/ckeditor5-dev-tests/package.json
- packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
Feature (tests): Added support for running automated tests for the TypeScript code. Closes ckeditor/ckeditor5#11716.
---
> Run tests for code written in TypeScript

- packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
Fix (tests): Properly detect console method usage in the asynchronous code and stop the whole test run if the `--production` flag is set.
---
> Properly detect console method usage in the asynchronous code

- packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
- packages/ckeditor5-dev-tests/tests/utils/manual-tests/getwebpackconfig.js
Feature (tests): Made it possible to run manual tests for features written in TS. Closes ckeditor/ckeditor5#11717.
---
> Made it possible to run manual tests for features written in TS

- packages/ckeditor5-dev-utils/lib/builds/getdllpluginwebpackconfig.js
- packages/ckeditor5-dev-utils/package.json
Other (utils): Adds support for TypeScript when building DLLs.
---
> Add support for TypeScript in DLL

- packages/ckeditor5-dev-tests/bin/check-dependencies.js
Fix (tests). Fixes usage of isDevDependency().
---
> Fix of usage of isDevDependency().

- packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
- packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
Internal (tests): Improved log message for building the DLLs for manual tests. Also, the output from the DLL build script is displayed in the terminal when manual test server started building DLLs. Closes ckeditor/ckeditor5#12469.
---
I decided to not build the DLLs in the development mode due to an error that is displayed in the terminal:
```
Module parse failed: 'import' and 'export' may only appear at the top level (15204:20)
File was processed with these loaders:
* ./node_modules/@ckeditor/ckeditor5-dev-tests/lib/utils/ck-debug-loader.js
You may need an additional loader to handle the result of these loaders.
|  */
|
> /* @if CK_DEBUG */  import { CKEditorError } from 'ckeditor5/src/utils';
|
| /**
```
Reported here: ckeditor/ckeditor5#12479.
> Improved log message for building the DLLs for manual tests

- packages/ckeditor5-dev-tests/bin/check-dependencies.js
Other (tests): The dependency checker should recognize `import type` as dev dependencies. Closes ckeditor/ckeditor5#12480.
---
> Dependency checker should recognize `import type` as dev dependencies.

- package.json
- packages/ckeditor5-dev-webpack-plugin/lib/servetranslations.js
- packages/ckeditor5-dev-webpack-plugin/package.json
Fix (webpack-plugin): Fixed the webpack compilation error while using the linked package. Closes ckeditor/ckeditor5#12887.
---
> Fixed webpack compilation error that happened while using linked package

- packages/ckeditor5-dev-webpack-plugin/lib/servetranslations.js
Fix (webpack-plugin): Restored building translation files introduced in [`v31.1.10`](https://github.com/ckeditor/ckeditor5-dev/releases/tag/v31.1.10). See ckeditor/ckeditor5#12887.
---
> Restored building translation files

- packages/ckeditor5-dev-webpack-plugin/lib/servetranslations.js
- packages/ckeditor5-dev-webpack-plugin/package.json
Fix (webpack-plugin): Proper detection of webpack 4. Closes ckeditor/ckeditor5#12887.
> Proper detection of webpack 4

- .travis.yml
- package.json
- packages/ckeditor5-dev-ci/bin/notifytravisstatus.js
Internal: Use `ckeditor5-dev-ci-notify-travis-status` script from new package `ckeditor5-dev-ci`.
---
> Use `ckeditor5-dev-ci-notify-travis-status` script from new package `ckeditor5-dev-ci`

- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
- packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
Reverts ckeditor/ckeditor5-dev#843.
> Revert "Fixed coverage with ck-debug flags"

- packages/ckeditor5-dev-dependency-checker/lib/checkdependencies.js
Fix (dependency-checker): The misplaced check should respect the `depcheckIgnore` option if specified when processing packages. Closes ckeditor/ckeditor5#13590.
> The misplaced check should respect the "depcheckIgnore" option

- packages/ckeditor5-dev-ci/lib/notifytravisstatus.js
Fix (ci): Fixed crash in the Travis notifier script if an author of a commit could not be obtained. Instead, ping the entire channel and mention an author from its name instead of a login that can be `null`.
> Fixed crash in the Travis notifier if an author of a commit could not be obtained

- packages/ckeditor5-dev-release-tools/lib/index.js
- packages/ckeditor5-dev-release-tools/lib/preparerepository.js
- packages/ckeditor5-dev-release-tools/lib/tasks/preparerepository.js
- packages/ckeditor5-dev-release-tools/package.json
- packages/ckeditor5-dev-release-tools/tests/tasks/preparerepository.js
Feature (release-tools): Added repository preparation script. Closes ckeditor/ckeditor5#13954.
> Added repository preparation script

- packages/ckeditor5-dev-release-tools/lib/index.js
- packages/ckeditor5-dev-release-tools/lib/tasks/push.js
- packages/ckeditor5-dev-release-tools/tests/tasks/push.js
Feature (release-tools): Added the push task. Closes ckeditor/ckeditor5#13958.
---
> Added the push task

- packages/ckeditor5-dev-release-tools/lib/tasks/preparerepository.js
- packages/ckeditor5-dev-release-tools/tests/tasks/preparerepository.js
Fix (release-tools): Fixed scoped package to have a flat structure in the release directory.
---
> Fixed scoped package to have a flat structure in the release dir.

- packages/ckeditor5-dev-ci/bin/circle-workflow-notifier.js
- packages/ckeditor5-dev-ci/lib/process-job-statuses.js
- packages/ckeditor5-dev-ci/package.json
- packages/ckeditor5-dev-ci/tests/process-job-statuses.js
Feature (ci): Introduced a CircleCI workflow notifier job for executing a task once all jobs within a workflow are completed.
---
> CircleCI job for executing a task once all jobs in a workflow are finished

- packages/ckeditor5-dev-build-tools/src/plugins/translations.ts
- packages/ckeditor5-dev-build-tools/tests/build/build.test.ts
Feature (build-tools): Update translations plugin to also output UMD build.
---
> Update `translations` plugin to also output UMD build

- packages/ckeditor5-dev-build-tools/src/plugins/replace.ts
- packages/ckeditor5-dev-build-tools/tests/plugins/replace/fixtures/replaced-dependency.js
- packages/ckeditor5-dev-build-tools/tests/plugins/replace/replace.test.ts
Feature (build-tools): Allow replacing imports before bundling.
---
> Feature (build-tools): Allow replacing imports before bundling.

- packages/ckeditor5-dev-build-tools/src/build.ts
- packages/ckeditor5-dev-build-tools/tests/build/build.test.ts
Fix (build-tools): UMD should respect output filename.
---
> Fix (build-tools): UMD should respect output filename.

- CHANGELOG.md
Docs: Changelog for v40.4.0.
---
> Changelog for v40.4.0

- CHANGELOG.md
Internal: Changelog for 40.5.0-alpha.0.
---
> Changelog for 40.5.0-alpha.0

- CHANGELOG.md
- README.md
Internal: Changelog for 40.5.0.
---
> Changelog for 40.5.0

- packages/ckeditor5-dev-build-tools/package.json
- packages/ckeditor5-dev-build-tools/vitest.config.ts
Internal: Update to Vitest@2.
---
> Internal: Update to Vitest@2

- CHANGELOG.md
Internal: Changelog for v42.0.0.
---
> Release v42.0.0

- CHANGELOG.md
Internal: Changelog for v42.0.1.
---
> Changelog for v42.0.1

- .github/workflows/codeql.yml
Internal: Updated the CodeQL configuration.
---
> Updated the CodeQL configuration

- packages/ckeditor5-dev-ci/package.json
- packages/ckeditor5-dev-dependency-checker/package.json
- packages/ckeditor5-dev-tests/package.json
Internal: Upgrade several dependencies.
---
> Upgrade several dependencies

- CHANGELOG.md
Internal: Changelog for v42.1.0.
---
> Changelog for v42.1.0

- CHANGELOG.md
Internal: Changelog for v43.0.0.
---
> Changelog for v43.0.0

- .eslintrc.js
- packages/ckeditor5-dev-stale-bot/bin/stale-bot.js
- packages/ckeditor5-dev-stale-bot/bin/utils/createspinner.js
- packages/ckeditor5-dev-stale-bot/bin/utils/parsearguments.js
- packages/ckeditor5-dev-stale-bot/bin/utils/parseconfig.js
- packages/ckeditor5-dev-stale-bot/bin/utils/validateconfig.js
- packages/ckeditor5-dev-stale-bot/lib/githubrepository.js
- packages/ckeditor5-dev-stale-bot/lib/utils/findstaledate.js
- packages/ckeditor5-dev-stale-bot/lib/utils/isissueorpullrequestactive.js
- packages/ckeditor5-dev-stale-bot/lib/utils/isissueorpullrequesttoclose.js
- packages/ckeditor5-dev-stale-bot/lib/utils/isissueorpullrequesttostale.js
- packages/ckeditor5-dev-stale-bot/lib/utils/isissueorpullrequesttounstale.js
- packages/ckeditor5-dev-stale-bot/lib/utils/ispendingissuestale.js
- packages/ckeditor5-dev-stale-bot/lib/utils/ispendingissuetostale.js
- packages/ckeditor5-dev-stale-bot/lib/utils/ispendingissuetounlabel.js
- packages/ckeditor5-dev-stale-bot/lib/utils/preparesearchquery.js
- packages/ckeditor5-dev-stale-bot/package.json
- packages/ckeditor5-dev-stale-bot/tests/githubrepository.js
- packages/ckeditor5-dev-stale-bot/tests/utils/findstaledate.js
- packages/ckeditor5-dev-stale-bot/tests/utils/isissueorpullrequestactive.js
- packages/ckeditor5-dev-stale-bot/tests/utils/isissueorpullrequesttoclose.js
- packages/ckeditor5-dev-stale-bot/tests/utils/isissueorpullrequesttostale.js
- packages/ckeditor5-dev-stale-bot/tests/utils/isissueorpullrequesttounstale.js
- packages/ckeditor5-dev-stale-bot/tests/utils/ispendingissuestale.js
- packages/ckeditor5-dev-stale-bot/tests/utils/ispendingissuetostale.js
- packages/ckeditor5-dev-stale-bot/tests/utils/ispendingissuetounlabel.js
- packages/ckeditor5-dev-stale-bot/tests/utils/preparesearchquery.js
- packages/ckeditor5-dev-stale-bot/vitest.config.js
Internal (stale-bot): Converted the package to ESM.
---
> Migrated `ckeditor5-dev-stale-bot` to ESM

- .eslintrc.js
- packages/ckeditor5-dev-web-crawler/lib/constants.js
- packages/ckeditor5-dev-web-crawler/lib/index.js
- packages/ckeditor5-dev-web-crawler/lib/runcrawler.js
- packages/ckeditor5-dev-web-crawler/lib/spinner.js
- packages/ckeditor5-dev-web-crawler/lib/utils.js
- packages/ckeditor5-dev-web-crawler/package.json
Internal (web-crawler): Converted the package to ESM.
---
> Migrated `ckeditor5-dev-web-crawler` to ESM

- .circleci/template.yml
Internal: Temporary changes to enable alpha release from the `epic/3757-esm` branch.
---
> Temporary changes to enable alpha release from the `epic/3757-esm` branch

- CHANGELOG.md
Internal: Changelog for v44.0.0.
---
> Changelog for v44.0.0

- .eslintrc.cjs
- package.json
- scripts/preparepackages.js
- scripts/publishpackages.js
Internal: Improved the `listr2` due to the recent ESM changes.
---
Part of https://github.com/cksource/ckeditor5-internal/issues/3827, but it is not related to the CKEditor 5 code itself.
> Improved the `listr2` due to the recent ESM changes

- CHANGELOG.md
- packages/ckeditor5-dev-release-tools/lib/utils/getnpmtagfromversion.js
- packages/ckeditor5-dev-release-tools/tests/utils/getnpmtagfromversion.js
Internal: Changelog for v44.2.1.
---
> Changelog for v44.2.1

- CHANGELOG.md
Internal: Changelog for v45.0.0.
---
> Changelog for v45.0.0

- CHANGELOG.md
Internal: Changelog for v45.0.1.
---
> Changelog for v45.0.1

- CHANGELOG.md
Internal: Changelog for v45.0.6.
---
> Changelog for v45.0.6

- CHANGELOG.md
Internal: Changelog for v45.0.7.
---
> Changelog for v45.0.7

- CHANGELOG.md
Internal: Changelog for v45.0.8.
---
> Changelog for v45.0.8

- CHANGELOG.md
Internal: Changelog v43.0.1.
---
> Changelog v43.0.1

- CHANGELOG.md
Internal: Changelog for v45.0.9.
---
> Changelog for v45.0.9

- CHANGELOG.md
Internal: Changelog for v45.0.10.
---
> Changelog for v45.0.10

- CHANGELOG.md
Internal: Changelog for v46.0.0.
---
> Changelog for v46.0.0.

- CHANGELOG.md
Internal: Changelog for v46.0.1.
---
> Changelog for v46.0.1

- CHANGELOG.md
Internal: Release for v46.0.3.
---
> Release for v46.0.3

- .circleci/template.yml
Internal: Introduced signing commits for CKEditorBot.
---
> Introduced signing commits for CKEditorBot

- packages/ckeditor5-dev-release-tools/tests/utils/getpackagespaths.js
- packages/ckeditor5-dev-tests/tests/utils/getrelativefilepath.js
- packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilescripts.js
- packages/ckeditor5-dev-tests/tests/utils/transformfileoptiontotestglob.js
- packages/ckeditor5-dev-utils/lib/styles/utils/getpackagename.js
- packages/ckeditor5-dev-utils/tests/styles/utils/getpackagename.js
Internal: Removed references to the CKEditor 5 build packages.
---
> Removed references to the build packages

- CHANGELOG.md
Internal: Changelog for v46.0.4.
---
> Changelog for v46.0.4

- CHANGELOG.md
Internal: Changelog for v46.0.6.
---
> Changelog for v46.0.6

- CHANGELOG.md
Internal: Changelog for v46.0.7.
---
> Changelog for v46.0.7

- .circleci/template.yml
Internal: Introduced signing tags.
---
> Introduced signing tags

- CHANGELOG.md
Internal: Changelog for v46.1.0.
---
> Changelog for v46.1.0

- CHANGELOG.md
Internal: Changelog for v47.0.0.
---
> Changelog for v47.0.0

- packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
- packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js
Feature (tests): Print more coverage information on CI. Related to ckeditor/ckeditor5#18034.
---
Before:
After:
> Feature (dev-tests): Print more coverage information on CI.

- CHANGELOG.md
Internal: Changelog for v47.1.0.
---
> Changelog for v47.1.0

- packages/ckeditor5-dev-translations/lib/utils/getlanguages.js
- packages/ckeditor5-dev-translations/tests/utils/getlanguages.js
Other (translations): Added the Belarusian language to the supported list. Closes ckeditor/ckeditor5#18229.
---
> Added the Belarusian language to supported list

- packages/ckeditor5-dev-ci/bin/circle-workflow-notifier.js
- packages/ckeditor5-dev-ci/lib/utils/is-workflow-finished.js
- packages/ckeditor5-dev-ci/tests/process-job-statuses.js
- packages/ckeditor5-dev-ci/tests/utils/is-workflow-finished.js
Other (ci): Support for jobs with the "skipped" status. Closes ckeditor/ckeditor5#18359.
---
> Support for jobs with the "skipped" status

- CHANGELOG.md
Internal: Changelog v48.0.0.
---
> Changelog v48.0.0

- CHANGELOG.md
Internal: Changelog for v49.0.0.
---
> Changelog for v49.0.0

- packages/ckeditor5-dev-web-crawler/src/constants.ts
Other (web-crawler): Ignore the requests related to the "if-cdn.com" service. Closes ckeditor/ckeditor5#18519.
---
* Prepare a local package: `yarn run release:prepare-packages --compile-only`
* Copy content from the `release/ckeditor5-dev-web-crawler/` directory to `cksource/docs/node_modules/@ckeditor`
* To check results, execute `yarn validate` in `cksource/docs`.
> Ignore the requests to/from `if-cdn.com`

- CHANGELOG.md
Internal: Changelog for v49.0.1.
---
> Changelog for v49.0.1

- CHANGELOG.md
Internal: Changelog for v49.0.2.
---
> Changelog for v49.0.2

- packages/ckeditor5-dev-build-tools/src/config.ts
- packages/ckeditor5-dev-build-tools/tests/build/build.test.ts
Internal (build-tools): Improve internal typing.
> Internal (build-tools): Improve internal typing.

- .changelog/20250710101255_improve_changelog_template.md
- packages/ckeditor5-dev-changelog/template/template.md
Improve changelog template.
---
* See ckeditor/ckeditor5#18777.
> Improve changelog template

- packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
- packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
- packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
*A brief summary of what this PR changes.*
---
* Closes #000
---
*Optional: Notes on decisions, edge cases, or anything helpful for reviewers.*
> Updated for cke5 root package migration

- .changelog/20251003145641_cc_8556_use_workspace_as_version.md
- CHANGELOG.md
> Changelog for v53.3.0.
