packages/ckeditor5-dev-env/lib/release-tools/changelog/parser-options.js
packages/ckeditor5-dev-env/lib/release-tools/changelog/writer-options.js
packages/ckeditor5-dev-env/tests/release-tools/changelog/transformcommit.js

Fix: Improvements for the changelog generator.
NOTE: During parsing the commits, the logger will inform about 3 statuses of the commit. Closes: #71.
NOTE: `'BREAKING CHANGE'` and `'BREAKING CHANGES'` will be grouped as `'BREAKING CHANGES'`. Closes: #73.

Minor improvements for parsing commits function.

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js

Internal: Disabled background timer throttling for automated tests. Closes #88.

T/88: Disable background throttling in Chrome

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js

Internal: Added `CHROME_LOCAL` browser which uses `--disable-background-timer-throttling` option for local environments. Fixes #88.
`CHROME_LOCAL` is used instead of `Chrome`.
---
The previous merge introduced the option only for CI.

T/88: Disable background throttling in Chrome (2)

---

lerna.json

Internal: Added `hoist` option to `lerna.json` in order to improve the speed of installing packages on CI. Closes #79.

T/79: Use deps hoisting to speed up installation time on CI 

---

packages/ckeditor5-dev-tests/bin/create-lerna-json.js

Internal: Use Lerna `hoist` option in order to improve the speed of installing packages on CI for ckeditor5-* packages. Closes #79.

T/79: Use deps hoisting to speed up installation time on CI (2)

---

packages/ckeditor5-dev-tests/bin/save-revision.js

Fix: Script for saving revision was not safe. Closes #125.
If git failed, the credentials data was printed to the public logs.

T/125: Use a more secure way to access GitHub on Travis

---

packages/ckeditor5-dev-tests/bin/save-revision.js

Internal: Changed commit message for commits made by script for saving revisions. Closes #127.

T127: The save-revision script could log a link to a commit that it's made

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js

Fix: Manual tests containing period in file name should not crash. Closes #135.

T/135 Fix problem with manual tests containing periods

---

packages/ckeditor5-dev-webpack-plugin/lib/index.js
packages/ckeditor5-dev-webpack-plugin/lib/replaceTranslationCallsForOneLanguage.js

Fixes https://github.com/ckeditor/ckeditor5-dev/issues/141.

Fix typo in `replaceTranslationCallsForOneLanguage`

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js

Fixes https://github.com/ckeditor/ckeditor5-dev/issues/135.
The glob pattern `globSync( path.join( sourceDir, '**', '*.!(js|html|md)' )` matches e.g. `someDir/ckeditor.es6.md`. It's hard for me to figure out the correct glob pattern for this match so I added the regexp exclusion.

T/135 Fix problem with manual tests containing dots in file names

---

packages/ckeditor5-dev-env/tests/translations/download.js
packages/ckeditor5-dev-utils/lib/translations/translationservice.js
packages/ckeditor5-dev-utils/tests/translations/createdictionaryfrompofilecontent.js
packages/ckeditor5-dev-utils/tests/translations/translationservice.js

Continuation of the https://github.com/ckeditor/ckeditor5-dev/pull/157 PR.
Closes #156
Provides 100% CC for the `ckeditor5-dev-utils/lib/translations/` and `ckeditor5-dev-env/lib/translations/` directories.

T/156b Increase code coverage in translation scripts. part 2.

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/parsearguments.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js

Feature: Added support for the `--server` option to the automated tests runner. Closes #165.

Added support for the --server option

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/getchangedfilesforcommit.js
packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubpackage.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/getchangedfilesforcommit.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubpackage.js

Fix:  Commits which changed files from a few packages will not be ignored now. `getChangedFilesForCommit()` returns a proper list of changed files for merge commits. Closes #172.

T/172: Merge commits are ignored when releasing sub packages

---

packages/ckeditor5-dev-bundler-rollup/package.json
packages/ckeditor5-dev-docs/package.json
packages/ckeditor5-dev-env/package.json
packages/ckeditor5-dev-lint/package.json
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-utils/package.json
packages/ckeditor5-dev-webpack-plugin/package.json
packages/jsdoc-plugins/package.json

Fix: Fixed invalid repository URL in package.json for all packages. Closes #171.

T171: Links to commits are incorrect in subpackages case

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsinglepackage.js
packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsubpackages.js
packages/ckeditor5-dev-env/lib/release-tools/utils/generatechangelogfromcommits.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/generatechangelogforsinglepackage.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/generatechangelogforsubpackages.js
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits.js

Internal: Fixed invalid comparison version links in the changelog. Closes #175.

T/175: Links to compare the versions for sub packages are invalid

---

packages/ckeditor5-dev-env/lib/release-tools/templates/footer.hbs
packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/parser-options.js
packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transform-commit-utils.js
packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubrepository.js
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits-integration.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transform-commit-utils.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubrepository.js

Fix: Complex commits will be parsed correctly. Closes #146.
---
This PR requires an integration test which was introduced in #180 so before reviewing this PR, **please merge the #180**.
A lot of our workaround for merge commits could be done using [`merge` option](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-parser#merge) for conventional-changelog (which parses the commits).
On the occasion, I changed:
- a color of commit ids displayed on the list during generating the changelog,
- swap an order of commit header and merge note for merge commits. Now the header of the commit will be displayed first. If the commit is a merge commit, below the line will be displayed a note about the merge.

T/146: Issues with generating changelog entries for more complex commits

---

packages/ckeditor5-dev-env/lib/release-tools/utils/changelog.js
packages/ckeditor5-dev-env/lib/release-tools/utils/versions.js
packages/ckeditor5-dev-env/tests/release-tools/utils/versions.js

Fix: Changelog's utils won't throw an error if the changelog file does not exist. Closes #187.

T/187: The changelog generator crashes on non-existen CHANGELOG.md

---

packages/ckeditor5-dev-env/lib/release-tools/templates/template.hbs
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits-integration.js

Fix: Changelog for internal changes will be followed by two blank lines instead of one. Closes #188.

T/188: Changelog entry generated by the release tool is followed by only one blank line

---

packages/ckeditor5-dev-env/lib/translations/collect-utils.js
packages/ckeditor5-dev-env/lib/translations/collect.js
packages/ckeditor5-dev-env/tests/translations/collect-utils.js
packages/ckeditor5-dev-env/tests/translations/collect.js

Fix: Added directory cleaning before pot files collecting. Closes #181.

Add directory cleaning before pot files collecting

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsinglepackage.js
packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsubpackages.js
packages/ckeditor5-dev-env/lib/release-tools/templates/template.hbs
packages/ckeditor5-dev-env/lib/release-tools/utils/cli.js
packages/ckeditor5-dev-env/lib/release-tools/utils/generatechangelogfromcommits.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/generatechangelogforsinglepackage.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/generatechangelogforsubpackages.js
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits-integration.js
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits.js

Feature: Added `internal` option to the version picker. Closes #184.
If you type `internal` as a new version during generating the changelog, all commits were made will be ignored.
---

T/184: Add "internal" option to the version picker 

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/releaserepository.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/releaserepository.js

Other: Release tool will use `npm version` command for bumping the version. Closes #213.
It allows using `preversion` and `postversion` hooks as npm scripts.

T/213: Release task should use `npm version` instead of `git tag`

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/getchangedfilesforcommit.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/getchangedfilesforcommit.js

Fix: A changed way for gathering changed files in a commit. Closes #207.

T/207: getChangedFilesForCommit() sometimes does not work as it should

---

packages/ckeditor5-dev-utils/lib/bundler/createentryfile.js
packages/ckeditor5-dev-utils/lib/bundler/geteditorconfig.js
packages/ckeditor5-dev-utils/package.json
packages/ckeditor5-dev-utils/tests/bundler/createentryfile.js
packages/ckeditor5-dev-utils/tests/bundler/geteditorconfig.js

Other: `createEntryFile()` util will use the "config" key from configuration file. Closes #217.
[Read more why it is required and important.](https://github.com/ckeditor/ckeditor5-build-classic/issues/10#issuecomment-303398682)
BREAKING CHANGE: `createEntryFile()` function does not accept the `configPath` argument any more. You need to pass the configuration object as `options.config` instead of it.
---
Required for https://github.com/ckeditor/ckeditor5-build-classic/pull/13.

T/217: Utils - Bundler - "createEntryFile" should use "config" key from configuration build

---

packages/ckeditor5-dev-lint/lib/utils/getgitignore.js
packages/ckeditor5-dev-lint/tests/utils/getgitignore.js

Feature: `getGitIgnore()` will transform directories to glob patterns. Closes #224.
Required in order to [use a more standard `"directory/"` notation in `.gitignore`](https://github.com/ckeditor/ckeditor5/issues/456).

T/224: [Lint] `getGitIgnore()` should transform directories as the glob patterns for Gulp

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubpackage.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubpackage.js

Fix: "Publish" commit will not be parsed during generate the changelog. Closes #220.

T/220: Changelog task shows the Publish commit

---

packages/ckeditor5-dev-bundler-rollup/README.md
packages/ckeditor5-dev-docs/README.md
packages/ckeditor5-dev-env/README.md
packages/ckeditor5-dev-lint/README.md
packages/ckeditor5-dev-tests/README.md
packages/ckeditor5-dev-utils/README.md
packages/ckeditor5-dev-webpack-plugin/README.md
packages/eslint-config-ckeditor5/README.md
packages/jsdoc-plugins/README.md

Internal: Added Changelog section to README. Closes #183.

T/183: Add "Changelog" section to each readme

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js
packages/ckeditor5-dev-env/lib/release-tools/utils/cli.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/releasesubrepositories.js
packages/ckeditor5-dev-env/tests/release-tools/utils/cli.js

Fix: `cli.confirmRelease()` shouldn't reject the promise if the user did not confirm the process. Closes #245.

T/245: Removed invalid Promise rejection

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/parser-options.js
packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transform-commit-utils.js
packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubrepository.js
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits-integration.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transform-commit-utils.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubrepository.js

Fix: Several issues related to proper typing the commit subject. Closes #270. Closes #271.
* If a commit didn't end with a dot, it was ignored. Now it will be handled.
* Added aliases for `Fix` type of the commit. Now `Fixes` and `Fixed` will be handled as `Fix`.
* Merge commit which wasn't a pull request was ignored. Now it will be handled.

Improvements for a changelog generator

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubpackage.js
packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubrepository.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubpackage.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubrepository.js

Fix: Merge commit which does not contain the second line will not crash the changelog tool. Closes #276.

T/276: Prevent from parsing invalid merge commit

---

packages/ckeditor5-dev-tests/bin/check-dependencies.js
packages/ckeditor5-dev-tests/bin/test-travis.sh
packages/ckeditor5-dev-tests/package.json

Feature: Adds "dependency-checker" which allows validating whether required dependencies are specified in package.json. Closes #278.
---
<details>
<summary>I run this tool for our packages. The result is below:</summary>
`editor-inline`
Error: The files listed below contain dependencies which are not defined in "package.json":
- ./tests/manual/tickets/23/1.js
Missing dev-dependencies:
- @ckeditor/ckeditor5-enter
- @ckeditor/ckeditor5-typing
- @ckeditor/ckeditor5-heading
- @ckeditor/ckeditor5-undo
---
`engine`
Error: The files listed below contain dependencies which are not defined in "package.json":
- ./tests/manual/tickets/880/1.js
- ./tests/manual/tickets/887/1.js
Missing dev-dependencies:
- @ckeditor/ckeditor5-essentials
---
`image`
Error: The files listed below contain dependencies …

T/278: Dependency Checker

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transform-commit-utils.js
packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubrepository.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transform-commit-utils.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubrepository.js

Fix: If a part of the comment matches to "organization/repository#id", this part will be replaced with a link which leads to the issue in the specified repository. Closes #269.

T/269: Autolinking GitHub repositories in the commit message

---

packages/ckeditor5-dev-docs/lib/index.js
packages/jsdoc-plugins/lib/custom-tags/observable.js
packages/jsdoc-plugins/lib/observable-event-fixer/addmissingeventdoclets.js
packages/jsdoc-plugins/lib/observable-event-provider/addmissingeventdocletsforobservables.js
packages/jsdoc-plugins/lib/observable-event-provider/index.js
packages/jsdoc-plugins/tests/observable-event-provider/addmissingeventdocletsforobservables.js

Feature: Provided support for `@observable` tag. Closes #285.

Provide support for `@observable` tag

---

packages/ckeditor5-dev-webpack-plugin/lib/replacetcalls.js
packages/ckeditor5-dev-webpack-plugin/lib/utils.js
packages/ckeditor5-dev-webpack-plugin/tests/utils.js

Fix: Fixed paths in webpack-plugin for Windows environment. Closes #297.

Fix paths in webpack-plugin for Windows environment

---

packages/jsdoc-plugins/lib/observable-event-provider/addmissingeventdocletsforobservables.js
packages/jsdoc-plugins/tests/observable-event-provider/addmissingeventdocletsforobservables.js

Fix: Add access property to events generated from observables. Closes #300.

Add access property to events generated from observables

---

packages/ckeditor5-dev-webpack-plugin/lib/replacetcalls.js

Fix: Made webpack plugin being able to run inside the ckeditor5-* package. Closes #302.

Make webpack plugin being able to run inside the ckeditor5-* package

---

README.md
package.json
packages/ckeditor5-dev-docs/bin/publish-nightly.js
packages/ckeditor5-dev-docs/lib/index.js
packages/ckeditor5-dev-docs/package.json
packages/ckeditor5-dev-env/README.md
packages/ckeditor5-dev-env/bin/translations.js
packages/ckeditor5-dev-env/lib/index.js
packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubrepository.js
packages/ckeditor5-dev-env/package.json
packages/ckeditor5-dev-env/tests/index.js
packages/ckeditor5-dev-tests/README.md
packages/ckeditor5-dev-tests/bin/install-dependencies.sh
packages/ckeditor5-dev-tests/bin/test-manual.js
packages/ckeditor5-dev-tests/bin/test.js
packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/removedir.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/webpacknotifierplugin.js
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/removedir.js
packages/ckeditor5-dev-utils/lib/logger.js
packages/ckeditor5-dev-utils/lib/tools.js
packages/ckeditor5-dev-utils/package.json
packages/ckeditor5-dev-utils/tests/logger.js
packages/ckeditor5-dev-utils/tests/tools.js
scripts/changelog.js

Other: Remove gulp dependency. Closes #296.
Now all packages are independent of gulp. Depending on usage you might either create "script " entry in pacakge.json to invoke bin executables or require library into script.
* Package `ckeditor5-dev-env` exposes new `translations` binary.
* Removed `gulp-jsdoc3` from building API documentation. Now `jsdoc` is invoked directly.
* Removed `options` param from logger methods. Logger no longer uses `gutil.log` method.
BREAKING CHANGE: Gulp is no longer required to run tasks from ckeditor5-dev-* packages use npm scripts instead.
BREAKING CHANGE: Gulp task are removed. New npm scripts were introduced.
---
Required for https://github.com/ckeditor/ckeditor5/pull/602.

T/296: Remove gulp dependency.

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js

Fix: Disabled initial compilation manual tests by the file watcher. Closes #318.

T/318: Disabled initial compilation MT by watcher

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js

Fix: Svg loader used in Webpack configuration for automated tests will work on Windows properly. Closes #323.

T/323: AT - Windows - SVG Loader

---

packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js

Revert: "T/290: Tests are executed as a single entry point" (https://github.com/ckeditor/ckeditor5-dev/commit/5fc685f).

Revert "T/290: Tests are executed as a single entry point"

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubrepository.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubrepository.js

Fix: Additional tags for continuous integration services that occurred in commit message will be removed during generating the changelog. Closes #309.

T/309:  [skip ci] will not occur in the generated changelog

---

packages/ckeditor5-dev-env/lib/release-tools/templates/template.hbs
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits-integration.js

Fix: Changelog generator for internal releases will always add two blank lines. Closes #308.

T/308: Added missing blank lines for internal notes

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatesummarychangelog.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/generatesummarychangelog.js

Fix: Links to releases will be generated correctly. Closes #310.

T/310: Invalid links to releases (changelog)

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubrepository.js

Fix: Additional notes will be removed from commit's footer. Closes #341.

T/341: Some tests fail after `lerna bootstrap`

---

packages/ckeditor5-dev-utils/lib/styles/themeimporter.js

Fix: Changed invalid regexp on Windows environments for importing themes (PostCSS). Closes #343.
---
Before merging this, check this out on Windows machine. It works for me but for unknown reasons may it does not work on your machine.

T/343: PostCSS does not work on Windows

---

.travis.yml
README.md
packages/ckeditor5-dev-tests/bin/install-dependencies.sh
packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js

Feature: Introduced Coveralls instead of CodeClimate. Closes #348.

T/348: Removed CodeClimate, introduced Coveralls

---

packages/jsdoc-plugins/lib/relation-fixer/addmissingdoclets.js
packages/jsdoc-plugins/lib/relation-fixer/buildrelations.js
packages/jsdoc-plugins/lib/relation-fixer/getmissingdocletsdata.js
packages/jsdoc-plugins/tests/relation-fixer/relationfixerintegration.js

Feature: JSDoc: Support extending typedefs. Closes #355.

JSDoc: Support extending typedefs

---

packages/ckeditor5-dev-webpack-plugin/lib/index.js
packages/ckeditor5-dev-webpack-plugin/tests/index.js

Other: Changed default output directory name for translations. Closes #354.
---
PRs / branches in other repositories:
https://github.com/ckeditor/ckeditor5-build-balloon/tree/t/ckeditor5-dev/354
https://github.com/ckeditor/ckeditor5-build-classic/tree/t/ckeditor5-dev/354
https://github.com/ckeditor/ckeditor5-build-inline/tree/t/ckeditor5-dev/354
https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-dev/354

Change default output directory name for translations

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js

Fix: BrowserStack will be disabled for PR builds that come from the community. Closes #358.

Disabled BrowserStack for community's PRs

---

packages/jsdoc-plugins/lib/observable-event-provider/addmissingeventdocletsforobservables.js
packages/jsdoc-plugins/tests/observable-event-provider/addmissingeventdocletsforobservables.js

Fix: Fixed inheritance in event doclets for observables. Closes #368.

Fix inheritance in event doclets for observables

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/template.html
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js

Feature: Implemented a responsive manual test layout with a 'back' button. Improved readability of the sidebar. Closes #369.

t/369: Implemented a responsive manual test layout with a 'back' button

---

packages/ckeditor5-dev-tests/bin/test-manual.js
packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/lib/utils/getrelativefilepath.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/createserver.js
packages/ckeditor5-dev-tests/tests/utils/getrelativefilepath.js
packages/ckeditor5-dev-utils/lib/styles/themeimporter.js
packages/ckeditor5-dev-utils/lib/styles/utils/getpackagename.js
packages/ckeditor5-dev-utils/tests/styles/utils/getpackagename.js

Fix: Manual tests server no longer depends on the directory name. It means that the whole project can be located under a path that doesn't have to ends with `ckeditor5`. Closes #351. Closes #381.

Manual test server will work properly if cwd does not ends with "ckeditor5"

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/releasesubrepositories.js

Fix: An invalid parameter was passed to the logger and it caused that logs were displayed incorrectly. Closes #380.

Fixed invalid logs in the release tool

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js

Internal: Removed babel loader rule from webpack's config when testing coverage. Closes #66.

Remove babel loader rule from webpack's config when testing coverage

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatesummarychangelog.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/generatesummarychangelog.js

Fix: The `Dependencies` header will not appear if any dependency has not been added or changed. Fixed also the invalid spacing between two versions in the generated changelog. Closes #398.

Fixed formating in changelog generated by "summary changelog generator"

---

packages/ckeditor5-dev-env/lib/release-tools/utils/creategithubrelease.js
packages/ckeditor5-dev-env/package.json
packages/ckeditor5-dev-env/tests/release-tools/utils/creategithubrelease.js

Other: Upgraded the `github` package that has been renamed to `@octokit/rest`. Closes #396.
---
I reviewed the release notes and there are no breaking changes for us.

Upgraded Github package (@octokit/rest")

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/releasesubrepositories.js

Fix: An error that occurs during publishing a package on GitHub will not break the whole process and the rest packages would be published. Closes #397.

Publishing package on GH will not break the process

---

packages/ckeditor5-dev-utils/lib/styles/getpostcssconfig.js

Fix: Disabled minify of CSS Animations (`@keyframes`). Closes #350.

Disabled minify of CSS animations in the postCSS config.

---

package.json
packages/ckeditor5-dev-env/package.json
packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-utils/lib/bundler/getlicensebanner.js
packages/ckeditor5-dev-utils/tests/bundler/getlicensebanner.js
packages/ckeditor5-dev-webpack-plugin/lib/ckeditor5-env-utils.js
packages/ckeditor5-dev-webpack-plugin/lib/servetranslations.js
packages/ckeditor5-dev-webpack-plugin/lib/translatesourceloader.js
packages/ckeditor5-dev-webpack-plugin/package.json
packages/ckeditor5-dev-webpack-plugin/tests/ckeditor5-env-utils.js
packages/ckeditor5-dev-webpack-plugin/tests/translatesourceloader.js

Other: Updated `CKEditorWebpackPlugin` to support webpack@4. Updated webpack in testing tools. Closes #371.
---
Changes in other repos:
* https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-dev/371 (https://github.com/ckeditor/ckeditor5/pull/1118)
* https://github.com/ckeditor/ckeditor5-build-classic/tree/t/ckeditor5-dev/371
* https://github.com/ckeditor/ckeditor5-build-inline/tree/t/ckeditor5-dev/371
* https://github.com/ckeditor/ckeditor5-build-balloon/tree/t/ckeditor5-dev/371
* https://github.com/ckeditor/ckeditor5-build-decoupled-document/tree/t/ckeditor5-dev/371
BREAKING CHANGE: Breaks compatibility with webpack v3.

Upgrade webpack plugin and testing environment for webpack v4 

---

packages/ckeditor5-dev-utils/lib/translations/multiplelanguagetranslationservice.js
packages/ckeditor5-dev-utils/tests/translations/multiplelanguagetranslationservice.js

Fix: compatiblity with extract-text-webpack-plugin. Closes #425
---
When using extract-text-webpack-plugin the getAssets function is called multiple times and the compilationAssets contain extract-text-webpack-plugin-name instead of the ckeditor.js.
Only one call of getAssets contains the ckeditor.js.
So i changed getAssets to return translations only when a valid script file is in compilation assets.

Fix: compatiblity with extract-text-webpack-plugin. Closes #425

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js

Internal: Add current timestamp to project name for builds on BrowserStack. Thanks to that, badges will always show a status of the latest build and its link open the build instead of the first created build.

Add current timestamp to project name for builds on BrowserStack

---

packages/ckeditor5-dev-tests/bin/save-revision.js

Fix: Disabled "save-revision" script for pull requests builds. Closes #434.

Disabled "save-revision" script for pull requests builds

---

packages/ckeditor5-dev-env/lib/release-tools/templates/header.hbs
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits-integration.js

Fix: Generated a changelog for the first time will have a proper link (in a header). Closes #430.
---
On the occasion, I've rewritten integration tests. Now they aren't depending on each other. When I was writing them for the first time I had a vision that wasn't correct. In fact, these tests cannot be executed using `it.only`. It forced to execute the entire chain what was a bad design.

Generated a changelog for the first time will have a proper link (in a header)

---

.travis.yml
lerna.json
package.json
packages/ckeditor5-dev-env/package.json
packages/ckeditor5-dev-tests/package.json
packages/jsdoc-plugins/package.json
scripts/changelog.js

Internal: Upgraded Lerna to 3.x due to an error that blocks publishing a new version of packages. Closes #441.

Upgraded Lerna to 3

---

packages/jsdoc-plugins/lib/validator/doclet-validator.js
packages/jsdoc-plugins/tests/doclet-validator.js

Feature: Added missing `@link` part validation to JSDoc validation. Closes #433.
---

Added missing @link part validation.

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js

Other: The `.rtf` files are now loaded via `raw-loader`. Closes #448.
---
None.

Load `.rtf` files via 'raw-loader' for automated tests.

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js

Fix: Small fixes for the tool that publishes the packages. Closes #445. Closes #446.
* For the real release, the tool won't ask about removing ZIP archives that are created when dry run mode is active. See #445.
* Publishing a package for the first time on GitHub will work properly. It didn't work because GitHub API returned `Not Found` response and the tool couldn't understand it. See #446.

Fixes for release tool after the last release

---

packages/eslint-config-ckeditor5/package.json

Fix: Use proper dependency version in eslint-config-ckeditor5 package. Closes #457.
---
* Still NPM package should be released for `eslint-plugin-ckeditor5-rules`

Fix dependency version in eslint-config-ckeditor5 package.

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js

Other: Enforce Edge 17 in BrowserStack tests.
---
* :crossed_fingers:

Use Edge 17.0 for BrowserStack tests.

---

packages/ckeditor5-dev-tests/bin/install-dependencies.sh
packages/ckeditor5-dev-tests/bin/link-package-to-node-modules.js
packages/ckeditor5-dev-tests/package.json

Fix: Link package inside its node_module's directory for tests. Closes #470.
---
For testing I did:
- clone the `ckeditor5-paragraph` repo
- `cd` into the created `ckeditor/ckeditor5-papragraph` directory
- run `yarn add ckeditor5-dev-test mgit2`
- run the `./node_modules/.bin/ckeditor5-dev-tests-create-mgit-json`
- run the `./node_modules/.bin/ckeditor5-dev-tests-add-workspace-to-package-json`
- run the `./node_modules/.bin/mgit sync --recursive --resolver-path=$(pwd)/node_modules/@ckeditor/ckeditor5-dev-tests/lib/mgit-resolver.js`
- run the `yarn install`
- run the test: `node --max_old_space_size=4096 node_modules/.bin/ckeditor5-dev-tests --coverage --reporter=dots --browsers=Chrome`
The test is failing with cannot add plugin twice (or simialar). The `./node_modules/` dir will contain …

Link package inside its node_module's directory for tests.

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js

Other: Add `'--js-flags="--expose-gc"'` flag to Karma Chrome launcher configuration. See ckeditor/ckeditor5#1341.
---
* This change is required for memory leak tests: https://github.com/ckeditor/ckeditor5-core/pull/155.

Add `--expose-gc` to Chrome's flags in Karma launcher configuration.

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/template.html

Internal: Enabled Content Security Policy settings in all manual tests (see ckeditor/ckeditor5#335).
---
Requires:
* https://github.com/ckeditor/ckeditor5-ckfinder/pull/36 changes in tests
* https://github.com/ckeditor/ckeditor5-theme-lark/pull/218 changes in tests

t/ckeditor5/335: Enabled Content Security Policy settings in all manual tests 

---

packages/ckeditor5-dev-tests/bin/prepare-mgit-json.js

Fix: Pull requests builds will use proper commit SHA-1. Instead of testing the merge commit which does not exist in the git tree, it will use the latest commit from a branch that a user wants to merge. Closes #484.
---
Testing PR and builds – https://github.com/ckeditor/ckeditor5-paragraph/pull/42.

Fixed PR builds in testing env

---

packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/attachinspector.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/copyassets.js
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js

Feature: Enabled ckeditor5-inspector in all manual tests. Closes #489.
---
NOTE: Awaits release of [ckeditor5-inspector](https://github.com/ckeditor/ckeditor5-inspector) on npm.

t/489: Enabled ckeditor5-inspector in all manual tests

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsinglepackage.js
packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsubpackages.js
packages/ckeditor5-dev-env/lib/release-tools/tasks/generatesummarychangelog.js
packages/ckeditor5-dev-env/lib/release-tools/utils/displaycommits.js
packages/ckeditor5-dev-env/lib/release-tools/utils/getnewreleasetype.js
packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubpackage.js
packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubrepository.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/generatechangelogforsinglepackage.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/generatechangelogforsubpackages.js
packages/ckeditor5-dev-env/tests/release-tools/tasks/generatesummarychangelog.js
packages/ckeditor5-dev-env/tests/release-tools/utils/displaycommits.js
packages/ckeditor5-dev-env/tests/release-tools/utils/getnewreleasetype.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubpackage.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubrepository.js

Fix: All commits will be displayed properly during generating the changelog. Closes #488.
---
I refactored a little bit the piece of the code because the next tickets will require it. No more side effect inside the `transformCommit()` function.

All commits will be displayed properly during generating the changelog

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubpackage.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubpackage.js

Fix: Non-scoped packages won't be ignored during the changelog generating. Closes #331.

Non-scoped packages won't be ignored during the changelog generating

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/attachinspector.js

Fix: Manual tests were crashing after setting `window.editor` to `null`. Closes #502.

Manual tests were crashing after setting window.editor to null

---

packages/ckeditor5-dev-env/lib/release-tools/utils/generatechangelogfromcommits.js
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits-integration.js

Feature: Multiple "Updated translations." commits will be merged into a single entry in the changelog. Closes #486.

Merged multiple "Updated translations" commits into one 

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transformcommitforsubrepository.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubrepository.js

Fix: `Merge 'stable' branch` commit will be ignored during generating the changelog. Closes #487.
---

"Merge 'stable' branch" commit will be ignored

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js

Other: Remove debug option for theme importer from manual tests webpack configuration. Closes ckeditor/ckeditor5#1654.
---
* Hides confusing logs.

Remove debug option for theme importer from manual tests webpack configuration.

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/bumpversions.js
packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js

Fix: Release tool will not crash when publishing a package for the first time. Closes #491.

Release tool will not crash when publishing a package for the first time

---

packages/ckeditor5-dev-tests/lib/utils/transformfileoptiontotestglob.js

Fix: Fixed code coverage matching for Windows. Closes #509.
---
`/` is always used as a separator for glob matchers, no matter the platform.
It would be nice to cover this fix with tests, this would require either setting a CI on appveyor.com or mocking path.sep. Either way I needed the fix asap, and need to switch to other tasks.

Fixed code coverage matching for Windows

---

packages/ckeditor5-dev-tests/bin/check-dependencies.js

Other: Introduced a parser for `*.css` files. Now it will check CSS files and if some package is missing, it will be printed by the dependency checker script. See ckeditor/ckeditor5#1662.

Dependency Checker will parse CSS files

---

packages/eslint-config-ckeditor5/.eslintrc.js

Other: Updated `ecmaVersion` from `es6` to `es2018` (`es9`). Changed the `space-before-function-paren` rule to preserve spaces before async arrow functions. Closes #521.
---
BREAKING CHANGE: During async arrow function linting, the space before the parenthesis will be required, unlike in the past.
The correct code style after this change:
```
const fn = function x() {};
const anonymousFn = function() {};
const arrowFn = () => {};
const asyncArrowFn = async () => {};
const asyncAnonymousFn = async function() {};
const asyncFn = async function y() {};
```

Change the `space-before-function-paren` rule to preserve spaces before async arrow functions

---

packages/ckeditor5-dev-tests/README.md
packages/ckeditor5-dev-tests/bin/test-travis.sh
packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/parsearguments.js
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js

Other: Removed the BrowserStack integration from `ckeditor5-dev` repository. See ckeditor/ckeditor5#1742.

Removed the BrowserStack integration from ckeditor5-dev repository

---

packages/ckeditor5-dev-env/lib/release-tools/utils/creategithubrelease.js
packages/ckeditor5-dev-env/tests/release-tools/utils/creategithubrelease.js

Fix: Adjusted usage of GitHub API inside `createGithubRelease()` util. Closes ckeditor/ckeditor5#1889.

Adjusted "createGithubRelease()" util to not use deprecated methods

---

packages/ckeditor5-dev-utils/lib/translations/findoriginalstrings.js
packages/ckeditor5-dev-utils/lib/translations/translatesource.js

Fix: Add ECMA version option to acorn parser options. Closes #534.
---
* Lack of ECMA specification caused problems with the usage of RegExp extensions: https://github.com/ckeditor/ckeditor5-utils/pull/292#discussion_r304822251

Add ECMA version option to acorn parser options.

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js

Feature: Added a proxy for static assets resources. Closes #139.
---
* Assets must be saved in `tests/_assets/` directory in the `@ckeditor/ckeditor5-utils` package.
* 13 repositories require changes in tests (modifying an image `[src]` attribute):
* The default asset: https://github.com/ckeditor/ckeditor5-utils/commit/7059a734c0c0529ec9ca7b129acc1c5d671ded28?short_path=6fe1ae4#diff-6fe1ae49b762910e195699e1e712cb30 (this file is specified in all changed tests)
* MrGit command for managing changes:
```console
mrgit --scope='@ckeditor/ckeditor5-@(alignment|block-quote|build-*|core|heading|highlight|media-embed|typing|ui)' exec 'git status -sb'
```

Added a proxy for static assets resources

---

packages/jsdoc-plugins/lib/validator/types.js

Other: Added `ErrorEvent` and `PromiseRejectionEvent` types to the JSDoc validator. Part of ckeditor/ckeditor5-watchdog#3.
---

Added ErrorEvent and PromiseRejectionEvent types to JSDoc validator

---

packages/ckeditor5-dev-tests/bin/prepare-mrgit-json.js
packages/ckeditor5-dev-tests/lib/bin/createmrgitjsoncontent.js
packages/ckeditor5-dev-tests/tests/bin/createmrgitjsoncontent.js

Fix: Forked repositories should be cloned properly on CI. Closes #542.

Forked repositories should be cloned properly on CI

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transform-commit-utils.js
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelogfromcommits-integration.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transform-commit-utils.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transform-commit/transformcommitforsubrepository.js

Other: Adjusted the changelog generator to match to planned changes related to merging issue trackers. Closes ckeditor/ckeditor5#1988.
BREAKING CHANGE: Due to merging our issue trackers, `pkgJson.bugs` will point to the same place for every package. We cannot rely on this value anymore. See ckeditor/ckeditor5#1988. Instead of we can take a value from `pkgJson.repository` and adjust it to match to our requirements.
---
This PR won't change anything in our project because we already have defined `pkgJson.repository` for each package but if somebody uses the tool and he hasn't defined the value, the tool will throw an ugly error and that's why I marked it as BC.

Adjusted the changelog generator to match to planned changes related to merging issue trackers

---

packages/jsdoc-plugins/lib/validator/validator.js

Fix: JSDoc validator will end with proper exit code if, during the validation, any error occurred. Closes #550.

JSDoc validator found errors, mark the entire process with proper exit code

---

packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/getrelativefilepath.js
packages/ckeditor5-dev-tests/lib/utils/transformfileoptiontotestglob.js
packages/ckeditor5-dev-tests/tests/tasks/runautomatedtests.js
packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/transformfileoptiontotestglob.js
packages/jsdoc-plugins/lib/validator/types.js
yarn.lock

Other: Adjusted dev tools to work with "ckeditor-" prefix. See ckeditor/ckeditor5#924.
---
In fact, we changed our private API so I don't think that those changes should be marked as BC.
Previously, `transformFileOptionToTestGlob()` returned a single path. Now it returns an array with two prefixes: `ckeditor5-` and `ckeditor-`. The rest of the changes are just adjusting tools to the new API.

Adjusted dev tools to work with "ckeditor-" prefix

---

packages/ckeditor5-dev-tests/bin/test-travis.sh

Fix: Fixed a script that extracts a package name from a current testing package. Now it uses a regular expression and works with `ckeditor-` prefix as well.

CKEditor 5 CI works with ckeditor- prefix

---

packages/ckeditor5-dev-tests/lib/bin/createmrgitjsoncontent.js
packages/ckeditor5-dev-tests/lib/mrgit-resolver.js
packages/ckeditor5-dev-tests/tests/bin/createmrgitjsoncontent.js

Fix: Mr. Git will handle "ckeditor-" packages on CI.
---
After learning mrgit how to handle "ckeditor-" packages, I was finally able to execute tests using the same script that Travis:

mrgit will handle "ckeditor-" packages on CI

---

packages/ckeditor5-dev-tests/bin/test-manual.js
packages/ckeditor5-dev-tests/lib/utils/getrelativefilepath.js
packages/ckeditor5-dev-tests/tests/utils/getrelativefilepath.js

Feature: Support for running manual tests from the main repository. See ckeditor/ckeditor5#2054.
In order to run manual tests for main package only, use `yarn run manual -f /`. By default, all tests (including the main package) are compiled.

Support for running manual tests from the main repository

---

packages/ckeditor5-dev-tests/README.md
packages/ckeditor5-dev-tests/lib/utils/automated-tests/parsearguments.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/parsearguments.js

Feature: Introduced two new CLI parameters: `--include-root` and `--only-root` that allow specifying whether the main repository should be added to test file query or tests from the main repository should be compiled only. It's a workaround due to bug in Git Bash (on Windows environment) that does not allow to use `'/'` as value for an option in CLI.  Closes #558.

Workaround for a bug related to `/` in Git bash (Win)

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js

Fix: Changed order of loaders in the webpack configuration for unit tests. Closes #https://github.com/ckeditor/ckeditor5/issues/5771.
---

Change order of loaders in the webpack configuration for unit tests

---

packages/ckeditor5-dev-tests/bin/test-travis.sh

Feature: Execute the `stylelint` task on CI. Closes #578.
Working build: https://travis-ci.org/ckeditor/ckeditor5-heading/builds/617103672

Execute stylelint task on CI

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js

Fix: RegExp pattern for coverage files now properly matches all ckeditor- and ckeditor5- projects. Closes #584.
---
It turned out that the RegExp created for all files was wrong. When no `--files` directive was passed the pattern was:
```
/ckeditor5-*\/src/
```
which doesn't catch packages names because `*` is a quantifier for `-` character.
The proper one is like:
```
/ckeditor5-[a-z-]+\/src/
```
ps.: dunno if we gonna have plugins like `ckeditor5-image-2` but I think that for now, we're safe :P

Fix files pattern for coverage when running without --files parameter.

---

packages/ckeditor5-dev-tests/README.md
packages/ckeditor5-dev-tests/bin/test-travis.sh
packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/leaksdetector.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/parsearguments.js
packages/ckeditor5-dev-tests/tests/tasks/runautomatedtests.js

Feature: Introduced automatic DOM leak detection for unit tests. Closes #586.
MAJOR BREAKING CHANGE: `--disallow-console-use` flag was removed, use `--production` instead.
---
See https://github.com/ckeditor/ckeditor5-dev/issues/586#issuecomment-571573488 for some notes.

Automatic DOM leak detection for unit tests

---

packages/ckeditor5-dev-env/lib/translations/collect-utils.js
packages/ckeditor5-dev-env/tests/translations/collect-utils.js
packages/ckeditor5-dev-utils/tests/translations/singlelanguagetranslationservice.js

Fix: Added support for the `"` character in translation messages and contexts. Closes #523.
---
I need to ensure that the `"` characters won't break during building the editor with the CKEditor5 webpack plugin.

Added support for the `"` character in translation messages and contexts

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js

Other: The inline `style` element which is being produced by Webpack and delivers styles for the editor will have the `[data-cke="true"]` attribute in order to help find CKEditor 5 styles. See ckeditor/ckeditor5#6454.

Added data-cke attribute to style selector

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js

Feature: Code coverage is also stored as a JSON file. Closes #615.

Code coverage is also stored as a JSON file

---

packages/stylelint-config-ckeditor5/.stylelintrc

Other: Configured stylelint to enforce CSS indentation using tabs and hsl() colors. Closes #611.
---
sub-PRs in v5 that fix stylelint errors (they can be merged regardless fo this PR):
* ckeditor5: https://github.com/ckeditor/ckeditor5/pull/6588
* theme-lark: https://github.com/ckeditor/ckeditor5-theme-lark/pull/278
* code-block https://github.com/ckeditor/ckeditor5-code-block/pull/12
* engine https://github.com/ckeditor/ckeditor5-engine/pull/1838
* highlight https://github.com/ckeditor/ckeditor5-highlight/pull/48
* pagebreak https://github.com/ckeditor/ckeditor5-page-break/pull/13
* widget https://github.com/ckeditor/ckeditor5-widget/pull/120
---
Let's make sure we release stylelint-config-ckeditor5 when this is all done (cc @pomek).

i/611: Configured stylelint to enforce CSS indentation using tabs and hsl() colors

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/leaksdetectorafter.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/leaksdetectorbefore.js

Other: The leak detector now prints the outerHTML of the elements leaked. Closes #617.
---
The outerHTML is cropped at 80 characters.
The check is a bit more precise now. Instead of just counting the elements, it checks precisely if new elements have been left in the dom after the test case.
With this patch, this is an example of the output I have:
```
ERROR: 'Elements leaked (1):
<div class="ck-filteredlist"><div class="select-menu-header d-flex"><span cla...
Be a good citizen and clean your DOM once you're done with it.'
```

Made the leak detector print the outerHTML of the elements leaked.

---

packages/ckeditor5-dev-utils/lib/translations/findmessages.js
packages/ckeditor5-dev-utils/tests/translations/findmessages.js

Fix: Added support for advanced structures of messages inside `t()` calls. Closes #622.
---
More information in the issue.

Add support for advanced structures of messages inside `t()` calls

---

packages/ckeditor5-dev-tests/bin/check-dependencies.js

Feature (tests): It's now possible to pass a custom path to the ckeditor5-dev-tests-check-dependencies bin as a CLI argument. Closes #630.

Allow to pass a custom path to the ckeditor5-dev-tests-check-dependencies bin as a CLI argument.

---

packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/createserver.js
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/createserver.js

Feature: Make port number configurable for manual tests server. Closes #632.
---
It's useful when running multiple servers on the same machine, or when one server hangs for unknown reasons. I also added a test for starting the server without any params.

Make port number configurable for manual tests server.

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js

Feature: Make port number configurable for automated tests server. Closes #637.
---
There are no tests for `getkarmaconfig.js`, should I create those, or just leave it as it is?

Make port number configurable for automated tests server. Closes #637.

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/bumpversions.js
packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js
packages/ckeditor5-dev-env/lib/release-tools/utils/creategithubrelease.js
packages/ckeditor5-dev-env/lib/release-tools/utils/getpackagestorelease.js
packages/ckeditor5-dev-env/lib/release-tools/utils/getsubpackagespaths.js
packages/ckeditor5-dev-env/lib/release-tools/utils/getsubrepositoriespaths.js
packages/ckeditor5-dev-env/tests/release-tools/utils/creategithubrelease.js
packages/ckeditor5-dev-env/tests/release-tools/utils/getpackagestorelease.js
packages/ckeditor5-dev-env/tests/release-tools/utils/getsubpackagespaths.js

Other: Adjusted release tools to handle single mono-repository architecture. Closes #606.

Release tools - monorepo

---

packages/ckeditor5-dev-tests/lib/utils/getrelativefilepath.js
packages/ckeditor5-dev-tests/tests/utils/getrelativefilepath.js

Fix (tests): The `getRelativeFilePath()` util will return proper paths for CKEditor 5 builds. Closes ckeditor/ckeditor5#7280. Closes ckeditor/ckeditor5#7093.

Manual test server will parse builds

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/bumpversions.js
packages/ckeditor5-dev-env/lib/release-tools/utils/validatepackagetorelease.js
packages/ckeditor5-dev-env/tests/release-tools/utils/validatepackagetorelease.js

Feature (env): Allows releasing packages from the non-master branch. Closes ckeditor/ckeditor5#7271.
Task `bumpVersions()` accepts `options.releaseBranch` (by default is `'master'`) which defined the branch using for releasing.

Allows releasing packages from the non-master branch

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/bumpversions.js

Feature (env): Release commit will trigger a Continuous Integration service. Closes ckeditor/ckeditor5#7302.

Release commit will trigger CI

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transformcommitfactory.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transformcommitfactory.js

Fix (env): The changelog generator will properly merge the `Closes` references. Closes ckeditor/ckeditor5#7298.
Fix (env): References to issues in additional commits will be merged and linked. See ckeditor/ckeditor5#7298.

Changelog generator will merge "Closes" references in fake commits

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsinglepackage.js

Fix: When typed "skip" as a new version, the changelog generator should abort the process instead of writing invalid entries to the changelog file. Closes ckeditor/ckeditor5#7402.

Changelog generator - "skip" breaks the process

---

packages/ckeditor5-dev-env/bin/translations.js
packages/ckeditor5-dev-env/lib/index.js
packages/ckeditor5-dev-env/lib/translations/download.js
packages/ckeditor5-dev-env/lib/translations/gettoken.js
packages/ckeditor5-dev-env/tests/index.js
packages/ckeditor5-dev-env/tests/release-tools/utils/executeonpackages.js
packages/ckeditor5-dev-env/tests/translations/download.js
packages/ckeditor5-dev-utils/lib/translations/multiplelanguagetranslationservice.js

Feature (env): Translation tools can handle external packages outside the CKEditor 5 repository. Closes ckeditor/ckeditor5#6635.
---
`getToken` returns now correctly a promise to a token instead a promise to `{ token }`.

Made the translations:download tools more generic

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transformcommitfactory.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transformcommitfactory.js

Other (env): Merge commits between `stable/release/master` branches will be ignored when generating the changelog. Those generate too much noise. Closes ckeditor/ckeditor5#7489.

Merge between stable/release/master should be ignored

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transformcommitfactory.js
packages/ckeditor5-dev-env/tests/release-tools/utils/transformcommitfactory.js

Fix (env): Scoped breaking changes notes won't be duplicated in the commit's footer. Closes ckeditor/ckeditor5#7495.
---
A commit used in the test is the same as what caused the problem.

Removed scoped BC notes from commit's footer

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogformonorepository.js
packages/ckeditor5-dev-env/lib/release-tools/utils/cli.js
packages/ckeditor5-dev-env/lib/release-tools/utils/getnewversiontype.js
packages/ckeditor5-dev-env/tests/release-tools/utils/cli.js

The changelog generator will use the same version for all packages in the mono repository project.
Other (env): The changelog generator for mono repository will use the same version for all packages. On the screen, a user will see all changes: `MAJOR BREAKING CHANGES`, `MINOR BREAKING CHANGES`, and all commits since the last release. The user must review it and provide the version. Closes ckeditor/ckeditor5#7323.
MAJOR BREAKING CHANGES (env): Task `generateChangelogForMonoRepository()` will generate the changelog uses the same version for all packages.

Changelog for monorepo - use the same version for all packages

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogformonorepository.js
packages/ckeditor5-dev-env/lib/release-tools/utils/getcommits.js
packages/ckeditor5-dev-env/tests/release-tools/utils/getcommits.js

Fix (env): The `getCommit()` util will return a proper array with commits if the release branch in the project is other than `master`. Due to `--first-parent` flag which is used for collecting the commits, when the release branch is other than `master`, commits made on `master` could not be collected directly from the branch. Now those commits are collected in two ranges: from the last tag to the [base commit](https://git-scm.com/docs/git-merge-base) and from the base commit to HEAD and merged together. Closes ckeditor/ckeditor5#7492.
Other (env): The `generateChangelogForMonoRepository()` task supports `options.releaseBranch` that is passed directly to the `getCommit()` util. See ckeditor/ckeditor5#7492.
---
For the specified tree:
```
7---8---9     <-- release
/
---1---2---3---4---5 …
```

Support for collecting commits from branches other than master

---

packages/jsdoc-plugins/lib/doclet.jsdoc
packages/jsdoc-plugins/lib/fix-code-snippets.js
packages/jsdoc-plugins/tests/fix-code-snippets.js

Fix: Added fixing code snippets for parameter, return, and property descriptions. Closes ckeditor/ckeditor5#7742.
---

Added fixing code snippets for parameter, return, and property descriptions

---

packages/ckeditor5-dev-env/lib/translations/createpotfiles.js
packages/ckeditor5-dev-utils/lib/translations/multiplelanguagetranslationservice.js
packages/ckeditor5-dev-utils/tests/translations/multiplelanguagetranslationservice.js
packages/ckeditor5-dev-webpack-plugin/README.md
packages/ckeditor5-dev-webpack-plugin/lib/index.js
packages/ckeditor5-dev-webpack-plugin/lib/servetranslations.js
packages/ckeditor5-dev-webpack-plugin/tests/index.js
packages/jsdoc-plugins/lib/doclet.jsdoc

Feature: Add support for the `translationsOutputFile` option for `CKEditorWebpackPlugin` allowing specifying the target bundle for translations. Closes ckeditor/ckeditor5#7688.
---
*   The `CKEditorWebpackPlugin` won't longer complain when no asset will be available during the build
*   Requires ckeditor/ckeditor5#7755.

Add support for the `translationsOutputFile` option allowing specifying target bundle for translations

---

packages/ckeditor5-dev-env/lib/translations/upload.js
packages/ckeditor5-dev-env/package.json
packages/ckeditor5-dev-env/tests/translations/upload.js
yarn.lock

Other (env): Improved output displayed while `translations.upload()` function is working. Instead of displaying `console.log()` after each package, summary tables will be displayed when the function finishes its job. Closes ckeditor/ckeditor5#7199.
---

Transifex.upload will print tables after all instead of console.logs

---

packages/ckeditor5-dev-docs/lib/index.js
packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/parsearguments.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilescripts.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/createserver.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/template.html
packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilescripts.js
packages/jsdoc-plugins/lib/purge-private-api-docs.js

Feature (tests): Manual test server accepts a new flag: `--identity-file` (alias: `-i`) that allows defining global constants in manual tests.
Other (tests): Manual test script will not search for tests in the `./manual/_utils` directory. If any of a manual test requires additional utils to work, those can be placed in the `_utils` directory.
Feature (jsdoc-plugins): Introduced a plugin that hides the package documentation if in the package's `package.json` file the `private` key is set to `true`. However, by adding the `@publicApi` annotation, you can mark blocks of the code that should not be hidden.
---
* A new `purge-private-api-docs` JSDoc plugin was introduced to remove private docs not ready to be public.

Provide changes required for env unification

---

packages/ckeditor5-dev-env/lib/release-tools/templates/template.hbs
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelog.js

Feature (env): The changelog generator now produces a commented out blog post placeholder by default. Closes ckeditor/ckeditor5#7954.
---
Didn't check the unit tests, I'll rely on CI here 🤞

The changelog generator now produces a commented out blog post placeholder by default

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/copyassets.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/template.html
packages/ckeditor5-dev-tests/lib/utils/manual-tests/togglesidebar.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js

Feature (tests): Implemented the toggle button for the manual tests sidebar. Closes ckeditor/ckeditor5#7962.
---
The state of the sidebar is stored in the `localStorage`.

#7962: Implemented the toggle button for the manual tests sidebar

---

packages/ckeditor5-dev-tests/README.md
packages/ckeditor5-dev-tests/lib/utils/automated-tests/parsearguments.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/parsearguments.js

Feature (tests): Introduced the `--repositories` (also known as `-r`) that allows specifying a name of a repository (or repositories, separated by a comma, similar to the `--files` option) where the tool should look for packages that should be tested. Thanks to that, you do not have to specify all packages of a repository that was cloned into the `external/` directory. Closes ckeditor/ckeditor5#7889.
An example. For the following tree:
```
packages/
...
ckeditor5-xyz
external/
custom-repository/
packages/
ckeditor5-foo/
ckeditor5-bar/
```
Executing a test command:
```
yarn run test --repositories custom-repository
``` 
will be translated to: 
```
yarn run test --files foo,bar
```
The `--repositories` option can be mixed with the `--files` option. The following command:
```
yarn run test …
```

Support for `--repositories` option

---

packages/eslint-config-ckeditor5/.eslintrc.js

Other: Enable "no-unused-expressions" ESLint rule. Closes ckeditor/ckeditor5#7843.

Enable "no-unused-expressions" ESLint rule.

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsinglepackage.js
packages/ckeditor5-dev-env/lib/release-tools/utils/getnewversiontype.js
packages/ckeditor5-dev-env/tests/release-tools/utils/getnewversiontype.js

Fix (env): The `getNewVersionType()` util will return a proper version when generating the changelog for a single package. Closes ckeditor/ckeditor5#8265.
Feature (env): `generateChangelogForSinglePackage()` accepts an optional option: `options.releaseBranch` (which is equal `master` by default).

`getNewVersionType()` will suggest proper version for "BREAKING CHANGES"

---

packages/ckeditor5-dev-tests/bin/check-dependencies.js

Other (tests): Improved linter error message for self-imports. Closes https://github.com/ckeditor/ckeditor5/issues/8245.
---
Example error message:

Improve self import linter error mesage

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogformonorepository.js

Feature (env): `generateChangelogForMonoRepository()` accepts new `options.skipLinks` (which is `false` by default) to omit release or commit links in generated changelog. Closes https://github.com/ckeditor/ckeditor5/issues/8167.

Provide an option to skip links in the changelog generator for monorepo packages

---

packages/jsdoc-plugins/package.json

Internal (jsdoc-plugins): Removed `jsdoc` from `peerDependencies`. Closes https://github.com/ckeditor/ckeditor5/issues/7870.
---
How to verify that locally:
1. In the `package.json` from `ckeditor5` repo provide a path to your local `ckeditor5-dev-docs` package: e.g. `"@ckeditor/ckeditor5-dev-docs": "file:../ckeditor5-dev/packages/ckeditor5-dev-docs"`.
2. In the `package.json` from `packages/jsdoc-plugins` from `ckeditor5-dev` repo provide a path to your local `jsdoc-plugins` package: e.g. `"@ckeditor/jsdoc-plugins": "file:../jsdoc-plugins"`.
3. From `ckeditor5` repo call `yarn --force` and confirm that `jsdoc@^3.6.0` unmet peer dependency is no longer displayed.

Removed `jsdoc` from `peerDependencies`

---

packages/ckeditor5-dev-env/bin/translations.js
packages/ckeditor5-dev-env/lib/translations/createpotfiles.js

Feature (env): Added the "--include-external-directory" to the `translations:collect` task that allows checking packages located in the "external/" directory. See ckeditor/ckeditor5#7901.

translations:collect – support for `external/` packages

---

packages/ckeditor5-dev-utils/lib/builds/getdllpluginwebpackconfig.js
packages/ckeditor5-dev-utils/lib/builds/getpluginwebpackconfig.js
packages/ckeditor5-dev-utils/lib/builds/index.js
packages/ckeditor5-dev-utils/lib/index.js
packages/ckeditor5-dev-utils/package.json

Internal (utils): Introduced a new object (`builds`) that contains a function (`getDLLPluginWebpackConfig()`) that returns a webpack configuration that uses DLL. See ckeditor/ckeditor5#8586.
---
Required for: https://github.com/ckeditor/ckeditor5/pull/8607

Initial version of the webpack config.

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js
packages/ckeditor5-dev-env/package.json

Feature (env): The idea of having "emptyReleases" has been changed to "customReleases" that allows specifying which files from the original package should be copied. Introduced the `options.customReleasesFiles` for the `releaseSubRepositories()` function. It allows specifying glob patterns of files that should be copied to the temporary directory from which the package will be published on npm. Closes ckeditor/ckeditor5#8616.
MAJOR BREAKING CHANGE (env): Renamed `options.packageJsonForEmptyReleases` to `options.packageJsonForCustomReleases` in the `releaseSubRepositories()` function.
MAJOR BREAKING CHANGE (env): Renamed `options.emptyReleases` to `options.customReleases` in the `releaseSubRepositories()` function.
---
Results for:
```js
require( '@ckeditor/ckeditor5-dev-env' ) …
```

Support for the "customReleasesFiles" option in "releaseSubRepositories()"

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogformonorepository.js

Fix (env): Changed packages in the generated changelog will be grouped to proper sections by exact comparing their scopes instead of matching values. Closes ckeditor/ckeditor5#8596.
---
The case mentioned in the issue was resolved:

Changed a way how the packages are grouped in the mono-repository changelog

---

packages/ckeditor5-dev-tests/bin/check-dependencies.js
packages/ckeditor5-dev-tests/package.json
yarn.lock

Fix (tests): Improved the dependency checker in detecting missing, unused, or misplaced packages from JS, CSS, and `package.json` files. Closes ckeditor/ckeditor5#8817.
---
Related PR is https://github.com/ckeditor/ckeditor5/pull/8854, which fixes errors found by this improved dependency checker.
The dependency checker is able to detect the new DLL-style imports, like `import { Plugin } from 'ckeditor5/src/core';`.
The `depcheck` version has been bumped to latest v1.3.1.
Fixes:
* Unused dependencies are now properly detected in JS or `package.json` files.
* Dependencies from CSS files are now properly detected and counted in the results.
Improvements:
* Misplaced dependencies `dependencies`  ⮀  `devDependencies` are now detected and reported.

Fixed dependency checker in detecting missing, unused or misplaced ones from JS, CSS and `package.json` files

---

packages/ckeditor5-dev-tests/bin/check-dependencies.js

Fix (tests): Minor improvements for the dependency checker that is available as a binary script of the package (`ckeditor5-dev-tests-check-dependencies`). Closes https://github.com/ckeditor/ckeditor5/issues/8862.
- Added a flag `--quiet` that allows display logs only if found issues with dependencies,
- If packages were not specified in arguments, all packages found in the `packages/` directory will be checked by default.
---
Related PR is https://github.com/ckeditor/ckeditor5/pull/8865, where the `--quiet` flag has been used.

Dependency checker improvements

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogformonorepository.js
packages/ckeditor5-dev-env/lib/release-tools/templates/commit.hbs
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelog.js

Feature (env): Support for collecting commits from additional mono-repositories in the `generateChangelogForMonoRepository()` function.
Thanks to the new option called `options.externalRepositories` which is an array of the `ExternalRepository` objects, you can specify additional repositories that should be checked while generating the changelog.
The `ExternalRepository` object requires the following properties:
* `{String}` `cwd` - An absolute path to the repository.
* `{String}` `packages` - Where to look for packages (a relative path to `cwd`)
The following properties are optional:
* `{String}` `scope` - Package names have to match to specified glob pattern in order to be processed.
* `{Array.<String>}` `skipPackages` - Name of packages which won't be touched.
* `{Boolean` `skipLinks` …

Support for collecting commits from external repositories in monorepo-changelog

---

packages/ckeditor5-dev-env/lib/release-tools/tasks/bumpversions.js
packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js

Feature (env): The `bumpVersions()` function can read the changelog file from an external directory (using `options.changelogDirectory`). Thanks to that, the private packages from the mono-repository can be released using a public changelog.
Feature (env): The `bumpVersions()` function allows skipping upgrading versions of dependencies between updated packages (using `options.skipUpdatingDependencies` which is `false` by default).
Fix (env): Simplified a check whether a package was published on NPM in the `releaseSubRepositories()` function. 
Other (env): The `bumpVersions()` function returns a promise with a collection that contains all updated packages. Previously the promise didn't resolve anything.
---
I'd like to do a live review because those scripts require much work that I don't …

Release tools can handle mono-repo that is a part of other mono-repo

---

packages/ckeditor5-dev-utils/lib/builds/getdllpluginwebpackconfig.js

Fix (utils): A DLL-consumer package produced by webpack should be assigned to the `window` object. See ckeditor/ckeditor5#9039.

Prepare a build that will be attached to the `window` object

---

packages/ckeditor5-dev-tests/bin/members.json
packages/ckeditor5-dev-tests/bin/notify-travis-status.js

Feature (tests): The `notify-travis-status` script will mention an author of a commit that caused to fail the CI.
---
More details about the implementation in the internal repo.

Ping an author of a commit that caused to fail the CI

---

packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/parsearguments.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/removedir.js
packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/removedir.js

Other (tests): Added the `--silent` flag to the manual test server that allows hiding names of the processed files. Closes ckeditor/ckeditor5#9220.

Added the "--silent" flag to the manual test server

---

packages/ckeditor5-dev-utils/lib/builds/getdllpluginwebpackconfig.js
packages/ckeditor5-dev-utils/tests/builds/getdllpluginwebpackconfig.js

Fix (utils): The webpack configuration returned by the `getDllPluginWebpackConfig()` function will not export the default library (`libraryExport`) anymore. See ckeditor/ckeditor5#9134.
MAJOR BREAKING CHANGE (utils): The `getDllPluginWebpackConfig()` function will not export the default library anymore. 
---

DLL: Removed `libraryExport` from the configuration

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/createserver.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/template.html
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js

Other (tests): Added the always visible button that navigates back to the list of manual tests. Refined the look of the list of manual tests. Closes ckeditor/ckeditor5#9843.
---
Go to ckeditor/ckeditor5#9843 to see what it looks like.

#9843: Improve the list of manual tests and in-test navigation

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/createserver.js

Tests: Replaced faulty regex. Closes ckeditor/ckeditor5#9849.

Replaced faulty regex.

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js

Internal (tests): Added proxies for `/example.com/image.png`, and `/www.example.com/image.png` URLs to serve the static image. Closes ckeditor/ckeditor5#8823.

Fixed HTTP#404 warnings in image tests.

---

packages/ckeditor5-dev-tests/bin/members.json
packages/ckeditor5-dev-tests/bin/notify-travis-status.js
packages/ckeditor5-dev-tests/package.json

Other (tests): The Slack notifier script will read the commit message from GitHub API for a particular commit. If the `SLACK_NOTIFY_COMMIT_URL` variable is specified, the value will be treated as the commit. Otherwise, a concatenation of `TRAVIS_REPO_SLUG`, and `TRAVIS_COMMIT` variables will be used.
Other (tests): The Slack notifier will print a message if a commit was made by a bot (as a result of merging branches).
Other (tests): The Slack notifier script will work if a commit comes from the `#stable` branch. 
---
Closes: Cs/C-I#781.

Several improvements for the Slack Notifier script

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js

Other (tests): Set watermarks for code coverage reports so anything less than 100% is instantly visible. Closes ckeditor/ckeditor5#9956.

Better CC watermarks

---

packages/ckeditor5-dev-env/lib/translations/createpotfiles.js
packages/ckeditor5-dev-env/tests/translations/createpotfiles.js

Other (env): Set the proper exit code when found an error when collecting translations. Closes ckeditor/ckeditor5#10123.

Exit code when `translations:collect` reports an error

---

packages/ckeditor5-dev-tests/bin/check-dependencies.js

Fix (tests): Prevented `isDevDependency()` function from reading "theme" word from the `ckeditor5-theme-lark` package name. See ckeditor/ckeditor5#9998.

Fixed incorrect path interpretation for theme-lark package

---

packages/ckeditor5-dev-docs/lib/web-crawler/index.js

Other (utils): The web-crawler configuration now allows ignoring HTTPS errors.
New options:
* `ignoreHTTPSErrors` - (optional) boolean passed to browser creator that allows ingoring HTTPS errors (e.g. when validating over HTTPS with self-signed certificate). Defaults to 'false'.
---
Required for: cksource/docs#394.

Added `ignoreHTTPSErrors` option for puppeteer lunch.

---

packages/ckeditor5-dev-utils/lib/builds/getdllpluginwebpackconfig.js
packages/ckeditor5-dev-utils/lib/translations/multiplelanguagetranslationservice.js
packages/ckeditor5-dev-utils/package.json
packages/ckeditor5-dev-utils/tests/builds/getdllpluginwebpackconfig.js
packages/ckeditor5-dev-utils/tests/translations/multiplelanguagetranslationservice.js
packages/ckeditor5-dev-webpack-plugin/README.md
packages/ckeditor5-dev-webpack-plugin/lib/index.js
packages/ckeditor5-dev-webpack-plugin/lib/servetranslations.js
packages/ckeditor5-dev-webpack-plugin/tests/index.js

Other (utils): The webpack configuration for DLL builds now produces the translation files.
Feature (webpack-plugin): Introduced several new options that improve the output files produced by the plugin.
New options:
* `corePackageContextsResourcePath` - (optional) a path to the file where all translation contexts are specified for the `ckeditor5-core` package. Defaults to `'@ckeditor/ckeditor5-core/lang/contexts.json'`.
* `includeCorePackageTranslations` - (optional) a flag that determines whether all translations found in the core package should be added to the output bundle file. If set to `true`, translations from the core package will be saved even if are not used in the source code (*.js files). Defaults to `false`.
* `skipPluralFormFunction`- (optional) a flag that determines …

Translations for DLL (dev)

---

packages/ckeditor5-dev-utils/lib/tools.js
packages/ckeditor5-dev-utils/tests/tools.js

Fix (utils): The `tools.clean()` function will resolve paths correctly on Windows environments. Closes ckeditor/ckeditor5#10141.

Fixed yarn clean script for Windows OS

---

packages/ckeditor5-dev-env/lib/release-tools/utils/generatechangelog.js
packages/ckeditor5-dev-env/lib/release-tools/utils/transformcommitfactory.js
packages/ckeditor5-dev-env/tests/release-tools/utils/generatechangelog.js

Fix (env): The "generateChangelog()" util will not crash when merging "Updated translations." commits found in the private repositories. Closes ckeditor/ckeditor5#10445.

Merging "Updated translations" from private repos should not crash

---

packages/ckeditor5-dev-env/lib/release-tools/utils/getpackagestorelease.js
packages/ckeditor5-dev-env/tests/release-tools/utils/getpackagestorelease.js

Fix: The `getPackagesToRelease()` function handles pre-release versions properly. Closes ckeditor/ckeditor5#10583.
---

`getPackagesToRelease()` handles pre-release versions

---

packages/ckeditor5-dev-env/lib/translations/upload.js
packages/ckeditor5-dev-env/tests/translations/upload.js

Fix (env): All numbers returned by the Transifex service will be cast to strings due to an error in the `cli-package`. See: Automattic/cli-table#152. Closes ckeditor/ckeditor5#10861.

Cast all numbers to strings when playing with the cli-table package

---

packages/jsdoc-plugins/lib/relation-fixer/getmissingdocletsdata.js

Fix (jsdoc-plugins): When detecting doclets of the same member, remove a prefix for instance/static symbols. Closes ckeditor/ckeditor5#8691.
---
The goal is to generate proper docs for the `DataController#set` method.
But the PR fixes all cases when a mixed method is overridden by a class. However, it's hard to say do we have more cases.

Remove instance/static symbols when comparing doclets

---

packages/ckeditor5-dev-tests/bin/test-manual.js
packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilescripts.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/copyassets.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilescripts.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-utils/tests/bundler/geteditorconfig.js
packages/jsdoc-plugins/tests/relation-fixer/buildrelations.js

Feature (tests): Added an option for disabling watchers in the manual test server. See: ckeditor/ckeditor5#10982.

Added an option for disabling watchers in the manual test server

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/getwebpackconfig.js

Fix (tests): Fixed generating source maps for manual and automated tests. Closes https://github.com/ckeditor/ckeditor5/issues/11006.
---
It looks like the webpack config for manual tests needs more fine grained configuration than the default one. So, instead of the `devtool` option, I manually added the [`SourceMapDevToolPlugin`](https://webpack.js.org/plugins/source-map-dev-tool-plugin) with some custom rules, where source map files are generated.
In automated tests, the only source map that works for me is `inline-source-map`.

Fixed generating source maps for manual and automated tests

---

packages/jsdoc-plugins/lib/purge-private-api-docs.js

Fix (jsdoc-plugins): Protected members should not be rendered in API docs. Closes ckeditor/ckeditor5#11143.
---

Do not render protected API docs

---

packages/ckeditor5-dev-docs/package.json
yarn.lock

Other (docs): Upgraded a version of the Puppeteer package to `13.1.3`. Closes ckeditor/ckeditor5#11014.
---
All working properly:
- ✔️ `yarn run docs:verify`
- ✔️ `yarn run manual:verify`
- ✔️ Crawler reports errors thrown in manual tests

Bumped Puppeteer version to `13.1.3`

---

packages/ckeditor5-dev-env/lib/tasks/bump-year.js

Other (env): Added handling for the `©` character when updating licenses. Closes ckeditor/ckeditor5#11119.

Added handling for the "©" character when updating licenses

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
yarn.lock

Fix (tests): Karma integrated with the IntelliJ IDE rebuilds the test bundle when detecting a change.
Fix (tests): Paths to files are clickable from a console if a test fails.
Fix (tests): Karma should not execute the test bundle twice when detecting a change (a macOS case).

Addressed issues with karma after upgrading to webpack 5

---

packages/ckeditor5-dev-env/lib/release-tools/utils/changelog.js
packages/ckeditor5-dev-env/tests/release-tools/utils/changelog.js

Fix (env): Fixed `changelog.getChangesForVersion()` util leaking to other releases. Closes ckeditor/ckeditor5#11322.
---

Fixed `changelog.getChangesForVersion()` util leaking to other releases

---

packages/ckeditor5-dev-env/lib/translations/transifex-service-for-api-v3.0.js
packages/ckeditor5-dev-env/lib/translations/upload.js
packages/ckeditor5-dev-env/package.json
packages/ckeditor5-dev-env/tests/translations/transifex-service-for-api-v3.0.js
packages/ckeditor5-dev-env/tests/translations/upload.js
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-utils/lib/tools/create-spinner.js
packages/ckeditor5-dev-utils/package.json
packages/ckeditor5-dev-utils/tests/tools/create-spinner.js
packages/ckeditor5-dev-webpack-plugin/package.json
yarn.lock

Feature (env): Redesigned the upload translations process. If a response from Transifex suggests that something went wrong, the script stores resources that couldn't be processed. When rerunning the script, packages listed in the file will be processed only.
Feature (tools): The `createSpinner()` function accepts a new option: `emoji`. It allows replacing the default one. Also, the `#finish()` method accepts the same option.
---
Transifex cannot process any of the packages, they will be stored in a file.
Rerun the script.
Finished with no errors.

Transifex migration to API v3.0 - Upload process

---

packages/ckeditor5-dev-docs/lib/web-crawler/index.js
packages/ckeditor5-dev-docs/lib/web-crawler/utils.js

Feature (docs): Web crawler shows the full console error that has been captured. Closes ckeditor/ckeditor5#11505.
Feature (docs): Web crawler listens to the `unhandledRejection` errors and marks the script execution as failed.
Other (docs): Web crawler can now properly serialize objects and iterables that are passed to the console.
---
We have decided that we will not introduce a new flag for these features, but enable them by default.

Web crawler - show full error message and detect the `unhandledRejection` error

---

packages/ckeditor5-dev-utils/lib/styles/getpostcssconfig.js
packages/ckeditor5-dev-utils/tests/styles/getpostcssconfig.js

Other (utils): Passed the `noIsPseudoSelector` option to `postcss-nesting` for backward compatibility in browsers that do not support CSS `:is()`. Closes #ckeditor/ckeditor5#11730.

Passed the `noIsPseudoSelector` option to `postcss-nesting`

---

packages/ckeditor5-dev-env/lib/translations/transifex-service.js
packages/ckeditor5-dev-env/package.json
packages/ckeditor5-dev-env/tests/translations/transifex-service.js

Other (env): Added new method `getResourceTranslations()` in `lib/translations/transifex-service.js` for fetching all current translations from Transifex for specified resource and language.
Other (env): Exposed new method `isSourceLanguage()` in `lib/translations/transifex-service.js` that checks if the specified language is the source language (English).
Internal (env): Bumped the `@transifex/api` package to v4.2.1.
---

Added new method for fetching all current translations from Transifex for specified resource and language

---

packages/ckeditor5-dev-env/lib/translations/transifex-service.js
packages/ckeditor5-dev-env/tests/translations/transifex-service.js

Fix (env): Added support for paginated resource translations results from Transifex. Closes ckeditor/ckeditor5#12098.
---

Added support for paginated resource translations results from Transifex

---

package.json
packages/ckeditor5-dev-utils/lib/translations/findmessages.js
packages/ckeditor5-dev-utils/package.json
packages/ckeditor5-dev-utils/tests/translations/findmessages.js

Internal: Support for TypeScript when collecting translation entries. Closes ckeditor/ckeditor5#12029.
---
It looks like `acorn`, even in the newest version, doesn't understand TypeScript sources.
TypeScript support is provided in another package - `@babel/parser`, and the `@babel` ecosystem has also a separate package for walking in the generated tree - `@babel/traverse`.
Initially, I thought it would be possible to prepare an `acorn`-compatible AST from the `@babel/parser` to re-use the existing `acorn-walk` package that currently finds all `t()` calls. According to the documentation from `@babel/parser` it should be possible, because it is shipped with the `estree` plugin, which produces the AST that is `acorn`-compatible. Unfortunately, it didn't quite work, because some deeply nested …

Support for TypeScript when collecting translation entries

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/parsearguments.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/parsearguments.js

Feature (tests): Added the `--resolve-js-first` option that prioritizes loading `*.js` over `*.ts` files for automated tests.
Feature (tests): Added the `--cache` option that enables webpack cache for automated tests. 
---

Added new CLI options for webpack config

---

packages/ckeditor5-dev-env/lib/release-tools/utils/transformcommitfactory.js
packages/ckeditor5-dev-env/package.json
packages/ckeditor5-dev-env/tests/release-tools/utils/transformcommitfactory.js

Feature (env): Split multi-scoped commit into multiple single-scoped commits, so the changelog generator can produce entries for all touched scopes. Closes ckeditor/ckeditor5#10605.
---

Split multi-scoped commit into multiple single-scoped commits

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js

Fix (tests): Fixed manual tests reloading twice on every save. Closes ckeditor/ckeditor5#12216.
---

Fixed manual tests reloading twice on every save

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/template.html

Other (tests): Manual tests should not load zoomed out on iOS. Closes ckeditor/ckeditor5#12438.

Manual tests should not load zoomed out on iOS

---

packages/ckeditor5-dev-docs/lib/docs/index.js
packages/ckeditor5-dev-docs/package.json
packages/jsdoc-plugins/LICENSE.md
packages/typedoc-plugins/CHANGELOG.md
packages/typedoc-plugins/LICENSE.md
packages/typedoc-plugins/README.md
packages/typedoc-plugins/lib/module-fixer/index.js
packages/typedoc-plugins/package.json
packages/typedoc-plugins/tests/module-fixer/fixtures/customerror.ts
packages/typedoc-plugins/tests/module-fixer/fixtures/error.ts
packages/typedoc-plugins/tests/module-fixer/fixtures/logger.ts
packages/typedoc-plugins/tests/module-fixer/fixtures/tsconfig.json
packages/typedoc-plugins/tests/module-fixer/index.js
packages/typedoc-plugins/tests/tsconfig.json
packages/typedoc-plugins/tests/utils.js
scripts/changelog.js

Feature (typedoc-plugins): Created the `@ckeditor/typedoc-plugins` package that contains plugins for the TypeDoc project.
Feature (typedoc-plugins): Added a module-fixer plugin that ensures a module name contains a proper value.

Created the @ckeditor/typedoc-plugins package

---

packages/ckeditor5-dev-docs/lib/docs/index.js
packages/ckeditor5-dev-docs/package.json
packages/typedoc-plugins/lib/module-fixer/index.js
packages/typedoc-plugins/lib/tag-error/index.js
packages/typedoc-plugins/package.json
packages/typedoc-plugins/tests/module-fixer/fixtures/customerror.ts
packages/typedoc-plugins/tests/module-fixer/fixtures/licenseonly.ts
packages/typedoc-plugins/tests/module-fixer/index.js
packages/typedoc-plugins/tests/tag-error/fixtures/customerror.ts
packages/typedoc-plugins/tests/tag-error/fixtures/error.ts
packages/typedoc-plugins/tests/tag-error/fixtures/tsconfig.json
packages/typedoc-plugins/tests/tag-error/index.js

Feature (typedoc-plugins): Created a package containing CKEditor 5 oriented plugins for `typedoc`. Closes ckeditor/ckeditor5#12522.
Feature (typedoc-plugins): Created the `module-fixer` plugin that reads a module name from the `@module` annotation. Closes ckeditor/ckeditor5#12523.
Feature (typedoc-plugins) Created the `tag-error plugin` that collects all occurrences of the `@error` tags in the CKEditor 5 code base. Closes ckeditor/ckeditor5#12525.
Other (docs): Bumped `typedoc` to `0.23`. Closes ckeditor/ckeditor5#12528.
---

Typedoc plugins

---

packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js

Internal (tests): Print a log once the DLL building process is finished.

Standardized the DLL build script

---

packages/ckeditor5-dev-docs/lib/docs/index.js
packages/typedoc-plugins/lib/tag-event/index.js
packages/typedoc-plugins/tests/tag-event/fixtures/customexampleclass.ts
packages/typedoc-plugins/tests/tag-event/fixtures/customexampleclassfires.ts
packages/typedoc-plugins/tests/tag-event/fixtures/custommodulewithoutclass.ts
packages/typedoc-plugins/tests/tag-event/fixtures/exampleclass.ts
packages/typedoc-plugins/tests/tag-event/fixtures/tsconfig.json
packages/typedoc-plugins/tests/tag-event/index.js

Feature (typedoc-plugins): Created the `tag-event` plugin that collects all occurrences of the `@eventName` tags in the CKEditor 5 code base. Closes ckeditor/ckeditor5#12526.
---
This plugin does not parse the `@event` tag, because it has a special meaning in the TypeDoc and it would be difficult to get it to work as we expect. This is why I added support for the custom `@eventName` tag, which now replaces the old `@event` tag.

Introduced new `tag-event` plugin for TypeDoc

---

packages/ckeditor5-dev-tests/bin/test-manual.js
packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/webpacknotifierplugin.js
packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js

Fix (tests): Disabled watch mode for building manual tests when no files are provided. Closes ckeditor/ckeditor5#12189.
---
* Moved default values for files from `bin/test-manual.js` to `lib/tasks/runmanualtests.js`.
* Added deduplication for file to test glob transform.
* Removed duplicated logic in tests

Fix (tests): Disable watch mode for building manual when no files provided

---

packages/ckeditor5-dev-docs/lib/docs/index.js
packages/typedoc-plugins/lib/tag-observable/index.js
packages/typedoc-plugins/tests/tag-observable/fixtures/customexampleclass.ts
packages/typedoc-plugins/tests/tag-observable/fixtures/exampleclass.ts
packages/typedoc-plugins/tests/tag-observable/fixtures/tsconfig.json
packages/typedoc-plugins/tests/tag-observable/index.js

Feature (typedoc-plugins): Created the `tag-observable` plugin that parses all occurrences of the `@observable` tag associated with class properties in the CKEditor 5 code base. Closes ckeditor/ckeditor5#12527.
---
To detect if the property is observable from Umberto point of view, a new helper could be introduced there:
```js
function isObservable( item ) {
// Check if the `@observable` tag is set.
if ( item.comment && item.comment.tags ) {
return item.comment.tags.some( tag => tag.tag === 'observable' );
}
return false;
};
```
Previously, I tried to add a new flag `isObservable` to TypeDoc, but it seems that it is not so easy. Flags in TypeDoc are stored as appropriate bit offsets on which some bit operations are performed, so adding a new flag from the outside may break everything.

Introduced new `tag-observable` plugin for TypeDoc

---

packages/ckeditor5-dev-docs/lib/docs/index.js
packages/typedoc-plugins/lib/event-inheritance-fixer/index.js
packages/typedoc-plugins/tests/event-inheritance-fixer/fixtures/class-a.ts
packages/typedoc-plugins/tests/event-inheritance-fixer/fixtures/class-b.ts
packages/typedoc-plugins/tests/event-inheritance-fixer/fixtures/class-c.ts
packages/typedoc-plugins/tests/event-inheritance-fixer/fixtures/class-d.ts
packages/typedoc-plugins/tests/event-inheritance-fixer/fixtures/tsconfig.json
packages/typedoc-plugins/tests/event-inheritance-fixer/index.js

Feature (typedoc-plugins): Introduced the `event-inheritance-fixer` plugin for TypeDoc that injects events in derived classes. Closes ckeditor/ckeditor5#12605.

Introduced the `event-inheritance-fixer` plugin that injects events in derived classes

---

packages/typedoc-plugins/lib/tag-event/index.js
packages/typedoc-plugins/lib/tag-observable/index.js
packages/typedoc-plugins/tests/event-inheritance-fixer/index.js
packages/typedoc-plugins/tests/event-param-fixer/index.js
packages/typedoc-plugins/tests/tag-event/index.js
packages/typedoc-plugins/tests/tag-observable/index.js

Internal: Aligned the `tag-event` and `tag-observable` plugins to not add the `event:` prefix for the event name.

Aligned the `tag-event` and `tag-observable` plugins to not add the `event:` prefix for the event name

---

packages/ckeditor5-dev-utils/lib/builds/getdllpluginwebpackconfig.js
packages/ckeditor5-dev-utils/tests/builds/getdllpluginwebpackconfig.js

Other (utils): Support for referencing DLLs built from TypeScript. Closes ckeditor/ckeditor5#12694.
---
This is required for https://github.com/ckeditor/ckeditor5/pull/12693.

Fixed support for referencing DLLs built from TypeScript.

---

packages/typedoc-plugins/lib/tag-event/index.js
packages/typedoc-plugins/tests/tag-event/fixtures/observableinterface.ts
packages/typedoc-plugins/tests/tag-event/index.js

Internal (typedoc-plugins): Added `change:{property}` and `set:{property}` events for the `Observable` interface. Closes ckeditor/ckeditor5#12722.
---
The source code in the `Observable` interface in CKEditor 5 has been aligned to required changes on the `ck/11721-build-API-from-typedoc` branch (renamed `event` → `eventName` and event docs are now associated with the exported type).
Now, both `change:{property}` and `set:{property}` events are properly associated with the `Observable` interface:

Added `change:{property}` and `set:{property}` events for the `Observable` interface

---

packages/ckeditor5-dev-utils/lib/builds/getdllpluginwebpackconfig.js
packages/ckeditor5-dev-utils/tests/builds/getdllpluginwebpackconfig.js

Fix (utils): The DLL configuration should reference backward compatible `*.js` files (not `*.ts`). See ckeditor/ckeditor5#12752.
---

The DLL reference should be backward compatible.

---

packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilescripts.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/requiredll.js
packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilescripts.js
packages/ckeditor5-dev-tests/tests/utils/requiredll.js

Fix (tests): When processing manual tests, if any of them require a DLL build, the manual test server adds the `DllReferencePlugin` plugin to the webpack configuration to avoid the duplicated modules error when using an import statement behind the `CK_DEBUG_*` flags. Closes ckeditor/ckeditor5#12791.

Load `DllReferencePlugin` when processing manual tests with DLL builds

---

packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilescripts.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/webpacknotifierplugin.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/websocket.js
packages/ckeditor5-dev-tests/lib/utils/requiredll.js
packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilescripts.js
packages/ckeditor5-dev-tests/tests/utils/requiredll.js

Fix (tests): When processing manual tests, if any of them require a DLL build, the manual test server adds the `DllReferencePlugin` plugin to the webpack configuration to avoid the duplicated modules error when using an import statement behind the `CK_DEBUG_*` flags. Closes ckeditor/ckeditor5#12791.
Other (tests): Split DLL and non-DLL manual tests to run separate webpack processes for both groups. They need to be compiled separately because DLL tests require `DllReferencePlugin`, and non-DLL ones must not have it.
---
Most of the code is taken from the ckeditor/ckeditor5-dev#809.

Load `DllReferencePlugin` when processing manual tests with DLL builds - next try

---

packages/typedoc-plugins/lib/module-fixer/index.js
packages/typedoc-plugins/lib/tag-error/index.js
packages/typedoc-plugins/tests/tag-error/index.js

Internal (typedoc-plugins): Unified the structures produced by `tag-error`. Closes ckeditor/ckeditor5#12724.
---
Follow-up to fix the numerical comparisons: ckeditor/ckeditor5#12877.

Unified the structures produced by `tag-error`

---

packages/typedoc-plugins/lib/module-fixer/index.js
packages/typedoc-plugins/lib/tag-error/index.js

Internal: Improved detection of module declaration and JSDoc link in Typedoc plugins. Instead of using numeric values, which are not constant, we now use enums exported from TypeScript. Closes ckeditor/ckeditor5#12877.

Improved detection of module declaration and JSDoc link in Typedoc plugins

---

packages/ckeditor5-dev-webpack-plugin/lib/translatesourceloader.js
packages/ckeditor5-dev-webpack-plugin/tests/translatesourceloader.js

Fix (webpack-plugin): Fixed generating source maps after switching the order of loaders in the CKEditor 5 translations webpack plugin. The source loader should pass through the source map object to avoid generating a new one. Closes ckeditor/ckeditor5#12928.
---

Translate source loader should pass through the source map object

---

.travis.yml
package.json
packages/ckeditor5-dev-bump-year/package.json
packages/ckeditor5-dev-ci/package.json
packages/ckeditor5-dev-dependency-checker/package.json
packages/ckeditor5-dev-docs/package.json
packages/ckeditor5-dev-release-tools/lib/index.js
packages/ckeditor5-dev-release-tools/lib/tasks/releasesubrepositories.js
packages/ckeditor5-dev-release-tools/package.json
packages/ckeditor5-dev-tests/bin/intellijkarmarunner/bin/karma
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-transifex/lib/index.js
packages/ckeditor5-dev-transifex/package.json
packages/ckeditor5-dev-translations/package.json
packages/ckeditor5-dev-utils/package.json
packages/ckeditor5-dev-web-crawler/lib/index.js
packages/ckeditor5-dev-web-crawler/package.json
packages/jsdoc-plugins/package.json

Internal: Cleanup after removed `ckeditor5-dev-env` and add missing exports for `web-crawler`, `transifex` and `release-tools`.
---

Cleanup after removed `ckeditor5-dev-env` and add missing exports for `web-crawler`, `transifex` and `release-tools`.

---

packages/ckeditor5-dev-tests/lib/utils/transformfileoptiontotestglob.js
packages/ckeditor5-dev-tests/tests/utils/transformfileoptiontotestglob.js

Internal: Do not execute `readdirSync` if directory does not exist for running tests.
---

Do not execute `readdirSync` if directory does not exist for running tests

---

packages/typedoc-plugins/lib/tag-error/index.js
packages/typedoc-plugins/tests/tag-error/fixtures/events.ts
packages/typedoc-plugins/tests/tag-error/index.js

Fix (typedoc-plugins): The `typedoc-plugin-tag-error` should not crash when processing error-like nodes, e.g., `@eventName error`. Closes ckeditor/ckeditor5#13362.

Error-like nodes should not crash the "tag-error" plugin

---

packages/typedoc-plugins/lib/tag-event/index.js
packages/typedoc-plugins/tests/tag-event/fixtures/customexampleclass.ts
packages/typedoc-plugins/tests/tag-event/index.js

Fix (typedoc-plugins): Fixed the `tag-event` plugin that crashed when trying to parse event parameters, which are passed as type arguments. Closes ckeditor/ckeditor5#13376.
---
It seems that the API docs that previously caused the crash are now generated correctly.
---
---

Fixed the `tag-event` plugin that crashed when trying to parse a complex events parameters

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js

Fix (tests): Disabled Chrome backgrounding optimizations in Karma config for automated tests to make the tests run in a stable environment that does not depend on the state of the browser window (focus vs. blur). Closes ckeditor/ckeditor5#13407.

Disabled Chrome backgrounding optimizations in Karma config for automated tests

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/getwebpackconfig.js

Fix (tests): Swapped an order of loaders when processing the TypeScript files. The `ck-debug-loader` is executed before `ts-loader` to avoid the removal of `CK_DEBUG_*` comments from the source code. See ckeditor/ckeditor5#13381.
MAJOR BREAKING CHANGE (tests): The code specified in the `CK_DEBUG_*` flags must be valid TypeScript code as it is processed before `ts-loader`.
---

Swapped order of ts-loader and ck-debug-loader

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js

Fix (tests): The `ck-debug-loader` should not be included in TypeScript files to avoid the "Unable to lookup source" error when checking the coverage. Instead, `babel-loader` should handle the `CK_DEBUG` flags. Closes ckeditor/ckeditor5#13529.

Fixed coverage with ck-debug flags

---

packages/ckeditor5-dev-release-tools/lib/tasks/releasesubrepositories.js
packages/ckeditor5-dev-release-tools/lib/utils/cli.js
packages/ckeditor5-dev-release-tools/tests/utils/cli.js

Feature (release-tools): Added a new option for the `releaseSubRepositories()` task that specifies the npm tag used when publishing packages to npm. Closes ckeditor/ckeditor5#13533.

Release tools support defining npm tag

---

packages/ckeditor5-dev-release-tools/lib/tasks/releasesubrepositories.js

Feature (release-tools): The `releaseSubrepositories()` task adds the `types` field (if not specified) to `package.json` while publishing packages based on the `main` field if a package is written in TypeScript. Closes ckeditor/ckeditor5#13518.
---

When publishing packages, adds the types field to pkg.json

---

packages/ckeditor5-dev-tests/lib/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/automated-tests/parsearguments.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilescripts.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/tasks/runmanualtests.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/parsearguments.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilescripts.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/getwebpackconfig.js

Other (tests): Allow specifying the `tsconfig` option in automated and manual tests. The path is resolved using the current working directory). If not specified, it will be resolved to default values that the `ts-config` resolves.

Allow specifying `tsconfig` path in automated tests

---

packages/ckeditor5-dev-docs/lib/build.js
packages/ckeditor5-dev-docs/lib/buildtypedoc.js
packages/ckeditor5-dev-docs/lib/validators/index.js
packages/ckeditor5-dev-docs/lib/validators/overloads-validator/index.js
packages/ckeditor5-dev-docs/tests/validators/overloads-validator/index.js

Other (docs): By default, the `@label` (overloads) validator is disabled when building docs from TypeScript. It can be enabled by passing the `validatorOptions: { enableOverloadValidator: true }` object as the configuration for the build task. Closes ckeditor/ckeditor5#13591.

Disabled the "@label" validator

---

packages/typedoc-plugins/lib/module-fixer/index.js
packages/typedoc-plugins/lib/purge-private-api-docs/index.js
packages/typedoc-plugins/lib/symbol-fixer/index.js
packages/typedoc-plugins/lib/tag-error/index.js
packages/typedoc-plugins/lib/tag-observable/index.js
packages/typedoc-plugins/package.json
packages/typedoc-plugins/tests/symbol-fixer/index.js

Other (typedoc-plugins): The package does not require any dependencies to prevent an integrator from using a specific version of `typedoc`. Instead, the integrator must install the `typedoc` package when using the `@ckeditor/typedoc-plugins` package. Closes ckeditor/ckeditor5#13511.
---

Typedoc-plugins is now dependency free

---

packages/ckeditor5-dev-release-tools/lib/index.js
packages/ckeditor5-dev-release-tools/lib/tasks/preparepackages.js
packages/ckeditor5-dev-release-tools/package.json

Feature (release-tools): Created a new task called `preparePackages()` that copies packages from the given directory to a temporary one that can be used as a source for publishing packages using the `releaseSubRepositories`() task. The primary goal of the new task is to prepare a TypeScript package to release as JavaScript.
---

Prepare packages to release script

---

packages/ckeditor5-dev-docs/lib/validators/module-validator/index.js
packages/ckeditor5-dev-docs/tests/validators/module-validator/fixtures/ckeditor5-example/src/augmentation.ts
packages/ckeditor5-dev-docs/tests/validators/module-validator/fixtures/ckeditor5-utils/src/augmentation.ts
packages/ckeditor5-dev-docs/tests/validators/module-validator/fixtures/tsconfig.json
packages/typedoc-plugins/lib/module-fixer/index.js
packages/typedoc-plugins/lib/purge-private-api-docs/index.js
packages/typedoc-plugins/lib/tag-error/index.js
packages/typedoc-plugins/lib/utils/index.js
packages/typedoc-plugins/tests/module-fixer/fixtures/not-valid-module.ts
packages/typedoc-plugins/tests/purge-private-api-docs/fixtures/private-package/src/not-valid-module.ts
packages/typedoc-plugins/tests/tag-error/fixtures/not-valid-module.ts

Fix (typedoc-plugins): The building documentation process should not crash when processing a non-es6 module file while building from the TypeScript sources. Closes ckeditor/ckeditor5#13662.
Fix (docs): The validator should not crash when processing a non-es6 module file while building from the TypeScript sources. Closes ckeditor/ckeditor5#13662.
---

Building docs when processing a non-es6 module

---

packages/ckeditor5-dev-web-crawler/package.json

Other (web-crawler): Upgraded Puppeteer to the latest version to avoid the deprecation warning when using the `@ckeditor/ckeditor5-dev-web-crawler` package. Closes ckeditor/ckeditor5#13631.
---
Crawler did its job properly and warning during `yarn install` is gone: [travis#598213237](https://app.travis-ci.com/github/ckeditor/ckeditor5/jobs/598213237)

Puppeteer version bump

---

packages/typedoc-plugins/lib/event-inheritance-fixer/index.js
packages/typedoc-plugins/lib/tag-observable/index.js
packages/typedoc-plugins/tests/event-inheritance-fixer/fixtures/class-foo.ts
packages/typedoc-plugins/tests/event-inheritance-fixer/fixtures/class-mixin-foo.ts
packages/typedoc-plugins/tests/event-inheritance-fixer/fixtures/class-mixin-foobar.ts
packages/typedoc-plugins/tests/event-inheritance-fixer/fixtures/mixin.ts
packages/typedoc-plugins/tests/event-inheritance-fixer/index.js
packages/typedoc-plugins/tests/tag-observable/index.js

Fix (typedoc-plugins): Improved inheriting (`typedoc-plugin-event-inheritance-fixer`) events from classes extending other classes using the mixin pattern. Closes ckeditor/ckeditor5#13739.
Fix (typedoc-plugins): Inherited observable properties (`typedoc-plugin-tag-observable`) will define the `inheritedFrom` property when an observable property is inherited. See ckeditor/ckeditor5#13739.

Improvements for inheriting events

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/package.json

Fix (tests): Fixed the reference error `Buffer is not defined`. Read more: webpack/changelog-v5#10.
---

Added buffer to webpack globals

---

packages/ckeditor5-dev-ci/lib/notifytravisstatus.js
packages/ckeditor5-dev-ci/package.json

Other (ci): Bumped a version of the `slack-notify` library.
Fix (ci): Fixed the `notifyTravisStatus()` function providing incorrect values for build times lasting 1 hour or longer.
---

Bumped slack-notify, fixed timestamp

---

packages/ckeditor5-dev-release-tools/lib/tasks/releasesubrepositories.js

Fix (release-tools): The `releaseSubRepositories()` task will now check the correct tag when checking what version is currently published on npm. Closes ckeditor/ckeditor5#13737.
---

Fetching version from npm now takes tag into account.

---

packages/ckeditor5-dev-release-tools/lib/tasks/releasesubrepositories.js
packages/ckeditor5-dev-release-tools/lib/utils/creategithubrelease.js
packages/ckeditor5-dev-release-tools/tests/utils/creategithubrelease.js

Other (release-tools): Mark GitHub release as a pre-release when publishing a non-latest version. Closes ckeditor/ckeditor5#13664.
---

Mark GitHub release as a pre-release when publishing a non-latest version

---

packages/typedoc-plugins/lib/tag-observable/index.js
packages/typedoc-plugins/tests/tag-observable/fixtures/exampleclass.ts
packages/typedoc-plugins/tests/tag-observable/index.js

Fix (typedoc-plugins): Properties with the `@observable` annotation hooked into accessor reflections were not processed when creating the `change:*` and `set:*` events.
---

Fixed missing accessor reflections

---

.gitignore
packages/ckeditor5-dev-release-tools/lib/index.js
packages/ckeditor5-dev-release-tools/lib/utils/executeinparallel.js
packages/ckeditor5-dev-release-tools/lib/utils/parallelworker.js
packages/ckeditor5-dev-release-tools/package.json
packages/ckeditor5-dev-release-tools/tests/utils/executeinparallel-integration.js
packages/ckeditor5-dev-release-tools/tests/utils/executeinparallel.js
packages/ckeditor5-dev-utils/lib/tools.js
packages/ckeditor5-dev-utils/lib/tools/createspinner.js
packages/ckeditor5-dev-utils/tests/tools.js
packages/ckeditor5-dev-utils/tests/tools/createspinner.js

Feature (release-tools): Introduced util called `executeInParallel()` that allows executing a task in parallel in all packages found in a directory specified in the configuration. See ckeditor/ckeditor5#13970.
Feature (utils): The `tools.createSpinner()` allows for creating a counter spinner that improves UX when executing a task specified the number of times.
---
- Example implementation: https://github.com/ckeditor/ckeditor5/pull/14031.

Created a util that allows executing a task in parallel

---

packages/ckeditor5-dev-web-crawler/lib/runcrawler.js

Other (web-crawler): Puppeteer no longer prints a warning regarding the Chrome Headless browser. See ckeditor/ckeditor5#14063.
---

Hidden the Puppeteer warning

---

packages/ckeditor5-dev-utils/lib/tools.js
packages/ckeditor5-dev-utils/tests/tools.js

Internal (utils): Added support for asynchronous command execution for `tools.shExec()` util. If the `async` (boolean) flag is set in command options, `tools.shExec()` returns a Promise, which is resolved with the command's output.
---

Added support for asynchronous command execution for `tools.shExec()`

---

packages/ckeditor5-dev-release-tools/lib/tasks/cleanuppackages.js
packages/ckeditor5-dev-release-tools/lib/tasks/commitandtag.js
packages/ckeditor5-dev-release-tools/lib/tasks/updatedependencies.js
packages/ckeditor5-dev-release-tools/lib/tasks/updateversions.js
packages/ckeditor5-dev-release-tools/lib/utils/executeinparallel.js
packages/ckeditor5-dev-release-tools/tests/tasks/cleanuppackages.js
packages/ckeditor5-dev-release-tools/tests/tasks/commitandtag.js
packages/ckeditor5-dev-release-tools/tests/tasks/updatedependencies.js
packages/ckeditor5-dev-release-tools/tests/tasks/updateversions.js
packages/ckeditor5-dev-release-tools/tests/utils/executeinparallel-integration.js
packages/ckeditor5-dev-release-tools/tests/utils/executeinparallel.js
packages/ckeditor5-dev-utils/lib/tools.js

Internal: Make release tools asynchronous. Closes ckeditor/ckeditor5#14135.

 Make release tools asynchronous

---

packages/ckeditor5-dev-release-tools/lib/utils/executeinparallel.js
packages/ckeditor5-dev-release-tools/tests/utils/executeinparallel.js

Internal (release-tools): `executeInParallel()` allows filtering out packages. See ckeditor/ckeditor5#14177.
---
Integration with CKEditor 5 is done in https://github.com/ckeditor/ckeditor5/pull/14195.

Re-build CKEditor 5 builds after updating references in the new release process

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/assertions/equal-markup.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/assertions/equal-markup.js

Fix (tests): Fixed `equalMarkup` assertion to print raw (unformatted) strings if formatted markup is equal. Closes ckeditor/ckeditor5#14175.
---
HTML beautification tools automatically remove extra whitespace characters inside tags (e.g. between attributes, after `<`, before `>`, etc.). It seems that this behavior cannot be adjusted. Apart from the `js-beautify` which we currently use, I checked also `diffable-html` (another popular tool for beautifying HTML) and there is also no control over whitespace inside tags.
For this reason, in case the formatted strings are the same, let's just display the raw (unformatted) strings.

Print raw strings if formatted markup is equal

---

packages/ckeditor5-dev-release-tools/lib/tasks/generatechangelogformonorepository.js
packages/ckeditor5-dev-release-tools/lib/utils/changelog.js
packages/ckeditor5-dev-release-tools/tests/utils/changelog.js

Feature (release-tools): Introduced util called `truncateChangelog()` that allows reducing the changelog to the requested number of entries. See ckeditor/ckeditor5#14169.
Internal: Generated changelog is truncated to the latest five release entries. Closes ckeditor/ckeditor5#14169.
---

Added support for truncating the changelog to the requested number of entries

---

packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilehtmlfiles.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/compilescripts.js
packages/ckeditor5-dev-tests/lib/utils/transformfileoptiontotestglob.js
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilescripts.js
packages/ckeditor5-dev-tests/tests/utils/transformfileoptiontotestglob.js

Other (tests): Support for running manual and automated tests written in TypeScript. Remember that test runners do not validate types as we use `esbuild` which ignores it. Closes ckeditor/ckeditor5#14170, ckeditor/ckeditor5#14171.
---

Added support for running manual and automated tests written in TS.

---

packages/ckeditor5-dev-utils/lib/builds/getdllpluginwebpackconfig.js
packages/ckeditor5-dev-utils/tests/builds/getdllpluginwebpackconfig.js

Fix (utils): When preparing a configuration for a DLL build, a JavaScript file should take precedence over the TypeScript version as it might differ from the source code. Closes ckeditor/ckeditor5#14335.

getDllPluginWebpackConfig() loads JS entry point if exists

---

packages/ckeditor5-dev-release-tools/lib/tasks/cleanuppackages.js
packages/ckeditor5-dev-release-tools/tests/tasks/cleanuppackages.js
scripts/preparepackages.js

Other (release-tools): Added the `preservePostInstallHook` option in the `cleanUpPackages()` task to preserve the `postinstall` hook in `package.json` in the published packages. Closes ckeditor/ckeditor5#14318.
---

Preserve `postinstall` hook in `package.json` in `cleanUpPackages()`.

---

package.json
packages/ckeditor5-dev-release-tools/lib/tasks/generatechangelogformonorepository.js
packages/ckeditor5-dev-release-tools/lib/tasks/generatechangelogforsinglepackage.js
packages/ckeditor5-dev-release-tools/lib/templates/template.hbs
packages/ckeditor5-dev-release-tools/lib/utils/generatechangelog.js
packages/ckeditor5-dev-release-tools/tests/utils/generatechangelog.js

Other (release-tools): The `highlightsPlaceholder` and `collaborationFeatures` options are no longer available in the `generateChangelogForMonoRepository()` and `generateChangelogForSinglePackage()` tasks.
---

Removing changelog elements.

---

packages/ckeditor5-dev-release-tools/lib/tasks/commitandtag.js
packages/ckeditor5-dev-release-tools/tests/tasks/commitandtag.js

Fix (release-tools): Add files to staging area one by one to avoid exceeding the maximum command length on Windows.
---

Release tools: Add files to staging area one by one to avoid exceeding the maximum command length on Windows

---

packages/ckeditor5-dev-ci/lib/format-message.js

Fix (ci): Fixed Slack notifiers displaying an incorrect message in case of a bot action. Closes ckeditor/ckeditor5#14669.
---

Fixed message in case of bot action

---

packages/ckeditor5-dev-utils/lib/loaders/index.js
packages/ckeditor5-dev-utils/tests/loaders/index.js

Fix (tests): Fixed generating the code coverage report if the project root directory differs from `ckeditor5`. 
Closes cksource/ckeditor5-internal#3483.
---

Fixed code coverage report for root project named `ckeditor5-*`.

---

packages/ckeditor5-dev-release-tools/lib/index.js
packages/ckeditor5-dev-release-tools/lib/tasks/updateversions.js
packages/ckeditor5-dev-release-tools/lib/utils/checkversionavailability.js
packages/ckeditor5-dev-release-tools/tests/index.js
packages/ckeditor5-dev-release-tools/tests/tasks/updateversions.js
packages/ckeditor5-dev-release-tools/tests/utils/checkversionavailability.js

Other (release-tools): Extracted `checkVersionAvailability()` function in release tools to a separate util that checks if provided version for a package already exists in npm.
---

Extracted `checkVersionAvailability()` in release tools to a separate util

---

packages/ckeditor5-dev-release-tools/lib/tasks/generatechangelogformonorepository.js

Feature (release-tools): Added the `skipFileSave` option to the `generateChangelogForMonoRepository()` function that allows returning the changelog entries instead of saving them into the changelog file. See ckeditor/ckeditor5#14601.
Feature (release-tools): Added  the `nextVersion` option to the `generateChangelogForMonoRepository()` function to pass a predefined version to the function. When using this option, the function no longer interacts with a user. See ckeditor/ckeditor5#14601.
---

Added nextVersion and skipFileSave options

---

packages/ckeditor5-dev-release-tools/lib/utils/executeinparallel.js

Internal: Make `listrTask` optional in `executeInParallel()` function. See cksource/ckeditor5-internal#3508.
---

Make `listrTask` optional in `executeInParallel()` function.

---

packages/ckeditor5-dev-ci/bin/allocate-swap-memory.sh
packages/ckeditor5-dev-ci/bin/install-latest-chrome.sh
packages/ckeditor5-dev-ci/package.json

Other (ci): Introduced the `ckeditor5-dev-ci-allocate-swap-memory` binary script for allocating the SWAP memory to avoid issues with running out of RAM.
Other (ci): Introduced the `ckeditor5-dev-ci-install-latest-chrome` binary script for installing the latest Chrome browser.
---

Introduced new scripts to configure CI.

---

packages/ckeditor5-dev-ci/lib/data/members.json
packages/ckeditor5-dev-ci/lib/format-message.js
packages/ckeditor5-dev-ci/tests/data/members.js
packages/ckeditor5-dev-ci/tests/format-message.js

Other (ci): The `formatMessage()` function should find a Slack account based on a GitHub name case-insensitive. Closes ckeditor/ckeditor5#14876.
Internal: GitHub members should not contain spaces.
---

Spaces in "members.json"

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js

Internal: Use `process.env.CI` to determine if a process is executed on CI when preparing a list of available browsers.
---

Use process.env.CI when defining browsers available on CI

---

packages/ckeditor5-dev-release-tools/lib/tasks/updatedependencies.js
packages/ckeditor5-dev-release-tools/lib/tasks/updateversions.js
packages/ckeditor5-dev-release-tools/lib/utils/executeinparallel.js
packages/ckeditor5-dev-release-tools/tests/tasks/updatedependencies.js
packages/ckeditor5-dev-release-tools/tests/tasks/updateversions.js

Feature (release-tools): The `updateVersions` and `updateDependencies` tasks accept a new option called `packagesDirectoryFilter`. It is a callback allowing filtering out directories/packages that the task should not touch. It receives an absolute path to a `package.json` and should return a boolean value.
---
See cksource/ckeditor5-commercial#5501.

Support for ignoring some packages in the release process

---

package.json
packages/typedoc-plugins/lib/event-inheritance-fixer/index.js
packages/typedoc-plugins/tests/event-inheritance-fixer/fixtures/interface-extends-type.ts
packages/typedoc-plugins/tests/event-inheritance-fixer/index.js

Fix (typedoc-plugins): Fixed `typedoc-plugin-event-inheritance-fixer` plugin to not crash when creating inherited events if an interface extends a type. Closes ckeditor/ckeditor5#15063.

Do not crash when creating inherited events when an interface extends a type

---

packages/ckeditor5-dev-release-tools/lib/utils/transformcommitfactory.js
packages/ckeditor5-dev-release-tools/tests/utils/transformcommitfactory.js

Fix (release-tools): The changelog generator will process a squash merge commit correctly. Before the change, the tool created an additional commit that didn't match a commit pattern. Hence, it's breaking changes notes were ignored. Closes ckeditor/ckeditor5#15056.

Support for processing squash commits

---

packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/getwebpackconfig.js

Fix (tests): UI in manual tests will now be fully translated in cases in which some translations come from external packages.
---

Fixed missing translations in manual tests.

---

packages/ckeditor5-dev-release-tools/lib/utils/transformcommitutils.js
packages/ckeditor5-dev-release-tools/tests/utils/transformcommitutils.js

Fix (release-tools): Fixed the `transformCommitUtils.linkToGithubIssue()` function to correctly match GitHub issue references that could look similar to HEX colors. Closes ckeditor/ckeditor5#14941.
---

Fixed `transformcommitutils.linkToGithubIssue()` incorrectly matching strings containing HEX colors

---

packages/ckeditor5-dev-release-tools/lib/tasks/publishpackages.js
packages/ckeditor5-dev-release-tools/lib/utils/assertpackages.js
packages/ckeditor5-dev-release-tools/tests/tasks/publishpackages.js
packages/ckeditor5-dev-release-tools/tests/utils/assertpackages.js

Feature (release-tools): The `publishPackages()` task accepts new options to ensure that packages define an entry point before publishing a new release. Closes ckeditor/ckeditor5#15127.
By default, the validator is disabled, but it can be changed by passing the `requireEntryPoint: true` value in the options object. Additionally, if any package does not define an entry point, the validator can skip such package by specifying its full name in the `optionalEntryPointPackages` array.
---

Release tools - an entry point validator

---

packages/ckeditor5-dev-docs/tests/validators/link-validator/fixtures/links.ts
packages/ckeditor5-dev-docs/tests/validators/link-validator/fixtures/types.ts
packages/ckeditor5-dev-docs/tests/validators/link-validator/index.js
packages/typedoc-plugins/lib/utils/index.js
packages/typedoc-plugins/package.json

Fix (docs): Typedoc linker validator should not emit a warning when a link points to a property defined as children of the `type` declaration. Closes ckeditor/ckeditor5#15321.
---

Typedoc linker does not emit a warning when linking to type's children

---

packages/ckeditor5-dev-bump-year/lib/bumpyear.js

Other (bump-year): The bump year script supports both _hyphen_ and _en dash_ symbols in the year range. Closes ckeditor/ckeditor5#15286.
---

Allowed different dash type in bump year script

---

packages/ckeditor5-dev-release-tools/lib/tasks/generatechangelogformonorepository.js
packages/ckeditor5-dev-release-tools/lib/tasks/generatechangelogforsinglepackage.js
packages/ckeditor5-dev-release-tools/lib/utils/changelog.js
packages/ckeditor5-dev-release-tools/package.json
packages/ckeditor5-dev-release-tools/tests/utils/changelog.js

Feature (release-tools): Allow defining the date format while preparing the changelog file. See ckeditor/ckeditor5#15429.
---

Support for defining the date format while preparing the changelog file

---

packages/ckeditor5-dev-translations/README.md
packages/ckeditor5-dev-translations/lib/ckeditortranslationsplugin.js
packages/ckeditor5-dev-translations/lib/servetranslations.js

Feature (translations): Compilation asset callback is now an optional field called `assetNamesFilter` in the object passed to the `CKEditorTranslationsPlugin` class. Thanks to that, it improves webpack compilation performance by filtering unrelated assets to reduce `TranslationService.getAssets()` calls. It only affects apps with many webpack entries and/or chunks.
---
```js
// webpack.config.js
module.exports = {
//...
plugins: [
new CKEditorTranslationsPlugin({
language: 'en',
additionalLanguages: 'all',
buildAllTranslationsToSeparateFiles: true,
assetNamesFilter: name => name === 'app.js'
})
]
//...
}
```
Fixed an error related to a service worker generated by [workbox-webpack-plugin](https://github.com/googlechrome/workbox) when the service worker asset got filtered out by the …

Add assetNamesFilter option

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/tests/utils/manual-tests/getwebpackconfig.js

Fix (tests): Force loading TypeScript files first when importing a file ending with the `.js` extension.
---
According to the error reported by the team member:
```
Module parse failed: Unexpected token (130:46)
File was processed with these loaders:
* ./node_modules/@ckeditor/ckeditor5-dev-translations/lib/translatesourceloader.js
* ./node_modules/@ckeditor/ckeditor5-dev-utils/lib/loaders/ck-debug-loader.js
You may need an additional loader to handle the result of these loaders.
|   */
|   _handleError(error, evt) {
>     /* @if CK_DEBUG */ const err = error as CKEditorError;
|     /* @if CK_DEBUG */ if ( err.is && err.is( 'CKEditorError' ) && err.context === undefined ) {
|     /* @if CK_DEBUG */ console.warn( 'The error is missing its context and Watchdog cannot restart the proper …
```

Load TS files first when importing a file containing the ".js" extension

---

packages/ckeditor5-dev-stale-bot/README.md
packages/ckeditor5-dev-stale-bot/bin/stale-bot.js
packages/ckeditor5-dev-stale-bot/bin/utils/parseconfig.js
packages/ckeditor5-dev-stale-bot/lib/githubrepository.js
packages/ckeditor5-dev-stale-bot/lib/graphql/searchpendingissues.graphql
packages/ckeditor5-dev-stale-bot/lib/utils/ispendingissuestale.js
packages/ckeditor5-dev-stale-bot/lib/utils/ispendingissuetostale.js
packages/ckeditor5-dev-stale-bot/lib/utils/ispendingissuetounlabel.js
packages/ckeditor5-dev-stale-bot/lib/utils/preparesearchquery.js
packages/ckeditor5-dev-stale-bot/tests/githubrepository.js
packages/ckeditor5-dev-stale-bot/tests/utils/ispendingissuestale.js
packages/ckeditor5-dev-stale-bot/tests/utils/ispendingissuetostale.js
packages/ckeditor5-dev-stale-bot/tests/utils/ispendingissuetounlabel.js
packages/ckeditor5-dev-stale-bot/tests/utils/preparesearchquery.js

Feature (stale-bot): Added support for pending issues so that they can be flagged sooner as stale ones. Closes ckeditor/ckeditor5#15697.
---

Stale bot - find and close `pending:feedback` issues

---

packages/ckeditor5-dev-stale-bot/README.md
packages/ckeditor5-dev-stale-bot/bin/stale-bot.js
packages/ckeditor5-dev-stale-bot/bin/utils/parseconfig.js
packages/ckeditor5-dev-stale-bot/lib/githubrepository.js
packages/ckeditor5-dev-stale-bot/tests/githubrepository.js

Fix (stale-bot): Start searching for stale issues without initial date set to allow removing stale labels from unlabeled pending issues. Closes ckeditor/ckeditor5#15812.
Other (stale-bot): Allow defining custom comment that is added to pending issues that are staled.
---

Stale bot does not remove the stale label from pending issues

---

packages/ckeditor5-dev-build-tools/src/plugins/splitCss.ts

Type: Message. Closes #000.
---

Remove `cssnano` warning and set `splitCss` code coverage to 100%.

---

packages/ckeditor5-dev-build-tools/src/config.ts
packages/ckeditor5-dev-build-tools/src/index.ts
packages/ckeditor5-dev-build-tools/src/plugins/emitCss.ts
packages/ckeditor5-dev-build-tools/src/plugins/splitCss.ts
packages/ckeditor5-dev-build-tools/tests/build/build.test.ts
packages/ckeditor5-dev-build-tools/tests/plugins/emitCss/emitCss.test.ts
packages/ckeditor5-dev-build-tools/tests/plugins/emitCss/fixtures/input-css.ts
packages/ckeditor5-dev-build-tools/tests/plugins/emitCss/fixtures/input.css
packages/ckeditor5-dev-build-tools/tests/plugins/emitCss/fixtures/input.ts
packages/ckeditor5-dev-build-tools/tests/plugins/emitCss/fixtures/tsconfig.json

Internal: Add `emitCss` plugin to emit empty CSS file if no file of given name was already emitted.
---

Add `emitCss` plugin

---

packages/ckeditor5-dev-build-tools/.gitignore
packages/ckeditor5-dev-build-tools/src/build.ts
packages/ckeditor5-dev-build-tools/tests/build/build.test.ts
packages/ckeditor5-dev-build-tools/tests/build/fixtures/dist/index.js

Feature (build-tools): Ability to set parameters `browser` and `outputName` for a build.
---

Extend CLI with `browser` and `outputName` parameters.

---

packages/ckeditor5-dev-utils/lib/loaders/index.js
packages/ckeditor5-dev-utils/package.json

Feature (dev-utils): Update `esbuild-loader` to ^4.1.0.
Feature (dev-utils): Set `target: es2022` in `esbuild-loader`.
---

Update esbuild-loader to ^4.1.0

---

packages/ckeditor5-dev-build-tools/src/config.ts

Feature (build-tools): Set `target:es2022` and `loose:false` in swc plugin to avoid syntax lowering and unnecessary code transformation.
Fix (build-tools): Prevent TypeScript plugin from processing the source code (which is already done by the swc plugin).
---

Set target to `es2022`

---

packages/ckeditor5-dev-build-tools/src/config.ts
packages/ckeditor5-dev-build-tools/tests/config/config.test.ts

Fix (build-tools): Properly detect "external" packages that contain dot in name.
---

Fix (build-tools): Properly detect "external" packages that contain dot in name.

---

packages/ckeditor5-dev-build-tools/src/config.ts
packages/ckeditor5-dev-build-tools/tests/config/config.test.ts

Fix (build-tools): Don't fail when `ckeditor5-premium-features` is in `external`, but not installed.
---

Fix (build-tools): Don't fail when `ckeditor5-premium-features` is in `external`, but not installed.

---

packages/ckeditor5-dev-release-tools/lib/index.js
packages/ckeditor5-dev-release-tools/lib/utils/versions.js
packages/ckeditor5-dev-release-tools/tests/index.js
packages/ckeditor5-dev-release-tools/tests/utils/versions.js

Other (release-tools): Added utils for fetching last pre-release version from npm (`getLastPreRelease()`) and generating next pre-release version (`getNextPreRelease()`).
---
Results from the real calls to npm for the `ckeditor5` package:
```
getLastPreRelease( "42.0.0-alpha" ) = null
getLastPreRelease( "37.0.0-alpha" ) = 37.0.0-alpha.3
getLastPreRelease( "0.0.0-nightly" ) = 0.0.0-nightly-20240531.0
getLastPreRelease( "0.0.0-nightly-20240101" ) = 0.0.0-nightly-20240101.0
getNextPreRelease( "42.0.0-alpha" ) = 42.0.0-alpha.0
getNextPreRelease( "37.0.0-alpha" ) = 37.0.0-alpha.4
getNextPreRelease( "0.0.0-nightly" ) = 0.0.0-nightly-20240531.1
getNextPreRelease( "0.0.0-nightly-20240101" ) = 0.0.0-nightly-20240101.1
getLastNightly() = 0.0.0-nightly-20240531.0
getNextNightly() = …
```

Dev tools: create a util for generating the next "pre-release" for given version

---

packages/ckeditor5-dev-release-tools/lib/utils/versions.js
packages/ckeditor5-dev-release-tools/tests/utils/versions.js

Fix (release-tools): Fixed the `getLastPreRelease()` function to handle pre-release versions with a multi-digit sequence number correctly. Closes ckeditor/ckeditor5#16576.
---

Sort package versions in natural way where multi-digit numbers are treated atomically

---

packages/ckeditor5-dev-build-tools/src/build.ts

Fix (build-tools): Fix banner path resolution that prevents the package from being built on Windows. Closes ckeditor/ckeditor5#16578.
---

Fix (build-tools): Fix banner path resolution on Windows.

---

packages/ckeditor5-dev-build-tools/src/plugins/splitCss.ts
packages/ckeditor5-dev-build-tools/src/utils.ts
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/import-data-image/body.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/import-data-image/input.ts
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/splitCss.test.ts
packages/ckeditor5-dev-build-tools/tests/utils.test.ts

Fix: Should not corrupt the CSS code during splitting CSS into editor and content files. See https://github.com/ckeditor/ckeditor5/issues/16670.
---

Fix for not adding a new line while parsing data:image CSS definitions.

---

packages/ckeditor5-dev-release-tools/lib/index.js
packages/ckeditor5-dev-release-tools/lib/tasks/verifypackagespublishedcorrectly.js
packages/ckeditor5-dev-release-tools/lib/utils/publishpackageonnpmcallback.js
packages/ckeditor5-dev-release-tools/tests/tasks/verifypackagespublishedcorrectly.js
packages/ckeditor5-dev-release-tools/tests/utils/publishpackageonnpmcallback.js

Feature (release-tools): Added a new task to verify if packages were published correctly to npm. See ckeditor/ckeditor5#16625.
---

Added new task to verify if package was published correctly to npm.

---

packages/ckeditor5-dev-release-tools/lib/utils/checkversionavailability.js
packages/ckeditor5-dev-release-tools/tests/utils/checkversionavailability.js

Fix (release-tools): The release tools is now compatible with npm 10. Closes ckeditor/ckeditor5#16610.
---

Fixed release tooling to be compatible with npm 10.

---

packages/ckeditor5-dev-release-tools/lib/tasks/verifypackagespublishedcorrectly.js
packages/ckeditor5-dev-release-tools/tests/tasks/verifypackagespublishedcorrectly.js

Internal: Fixed logic in `verifyPackagesPublishedCorrectly` to use `checkVersionAvailability` correctly. See ckeditor/ckeditor5#16625.
---

Fixed logic in `verifyPackagesPublishedCorrectly` to use `checkVersionAvailability` correctly.

---

packages/ckeditor5-dev-build-tools/src/plugins/splitCss.ts
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/nested-css-variables/file1.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/nested-css-variables/input.ts
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/splitCss.test.ts

Fix (build-tools): Preserve CSS variables used by other CSS variables when splitting styles into editor- or content-only stylesheets. Fixes [ckeditor/ckeditor5#16689](https://github.com/ckeditor/ckeditor5/issues/16689).
---

Fix (build-tools): Keep nested CSS variables when splitting stylesheets into editor- or content-only stylesheets.

---

packages/ckeditor5-dev-ci/lib/trigger-circle-build.js
packages/ckeditor5-dev-ci/tests/trigger-circle-build.js

Fix (dev-ci): Improved error handling by checking both error properties for the `triggerCircleBuild()` util. Closes ckeditor/ckeditor5#16746.
---

Improved error handling for `triggerCircleBuild()`.

---

packages/ckeditor5-dev-build-tools/package.json
packages/ckeditor5-dev-build-tools/src/config.ts
packages/ckeditor5-dev-build-tools/src/plugins/splitCss.ts
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/combine-root-definitions/file1.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/combine-root-definitions/file2.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/combine-root-definitions/input.ts
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/keyframes/file1.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/keyframes/file2.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/keyframes/input.ts
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/media-query/file1.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/media-query/file2.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/media-query/input.ts
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/more-than-one-selector/file1.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/more-than-one-selector/input.ts
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/nested-css-variables/file1.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/omit-root-definitions/file1.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/fixtures/omit-root-definitions/file2.css
packages/ckeditor5-dev-build-tools/tests/plugins/splitCss/splitCss.test.ts

Fix (build-tools): Should preserved all needed selectors and at-rules in CSS files after split into editor and content stylesheets. Closes https://github.com/ckeditor/ckeditor5/issues/16703.
---
The main problem was when we were splitting main css file into `editor` and `content`. Mainly it was done using `.ck-content` CSS class as a main target what should be put into `content` file and all the rest should land into `editor`. But this condition didn't include neither `@media` queries or  animations with `@keyframes` that class contains.
First approach was to write it by us (PR: https://github.com/ckeditor/ckeditor5-dev/pull/972) but it was a lot of code and it wans't bullet proof for future. So decision was made to try something else: `PurgeCss` lib.
With using `PurgeCss` all at-rules …

New approach to separating editor and content CSS

---

packages/ckeditor5-dev-build-tools/src/plugins/translations.ts
packages/ckeditor5-dev-build-tools/tests/plugins/translations/translations.test.ts
packages/ckeditor5-dev-dependency-checker/lib/checkdependencies.js

Fix (dependency-checker): Treat dependencies in the `dist` folder as production dependencies. See ckeditor/ckeditor5#16646.
Other (build-tools): The `.d.ts` files for translations should import directly from `@ckeditor/ckeditor5-utils` instead of `ckeditor5`. See ckeditor/ckeditor5#16646.
MINOR BREAKING CHANGE: Treat dependencies in the `dist` folder as production `dependencies`.
---

Treat dependencies in the `dist` folder as production dependencies.

---

packages/ckeditor5-dev-build-tools/README.md
packages/ckeditor5-dev-build-tools/src/build.ts
packages/ckeditor5-dev-build-tools/src/utils.ts
packages/ckeditor5-dev-build-tools/tests/build/arguments.test.ts
packages/ckeditor5-dev-build-tools/tests/build/build.test.ts
packages/ckeditor5-dev-build-tools/tests/config/config.test.ts

Fix (build-tools): Ability to pass `globals` parameter if necessary for external imports in `umd` bundles. See https://github.com/ckeditor/ckeditor5/issues/16798.
BREAKING CHANGE: Ability to pass `globals` parameter if necessary for external imports in `umd` bundles.
---

Build tools extended with the ability to pass the globals parameter.

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getkarmaconfig.js

Fix (dev-tests): Added a Chrome flag to prevent displaying the search engine choice screen that disrupts automated tests in windowed mode. Closes https://github.com/ckeditor/ckeditor5/issues/16825.

Added a Chrome flag to prevent displaying the search engine choice screen

---

packages/ckeditor5-dev-stale-bot/lib/githubrepository.js
packages/ckeditor5-dev-stale-bot/lib/graphql/getlabels.graphql
packages/ckeditor5-dev-stale-bot/tests/githubrepository.js

Other (stale-bot): Aligned stale bot to recent changes in the GitHub GraphQL API in the `repository.labels` connection. GitHub recently started returning a lot of mismatched labels for the query and now stale bot ensures that only the required ones are used. Closes ckeditor/ckeditor5#16872.
---

Aligned stale bot to recent changes in the GitHub GraphQL API

---

packages/ckeditor5-dev-build-tools/src/build.ts
packages/ckeditor5-dev-build-tools/src/config.ts
packages/ckeditor5-dev-build-tools/src/index.ts
packages/ckeditor5-dev-build-tools/src/plugins/loadSourcemaps.ts
packages/ckeditor5-dev-build-tools/src/utils.ts
packages/ckeditor5-dev-build-tools/tests/_utils/utils.ts
packages/ckeditor5-dev-build-tools/tests/plugins/banner/banner.test.ts
packages/ckeditor5-dev-build-tools/tests/plugins/emitCss/emitCss.test.ts
packages/ckeditor5-dev-build-tools/tests/plugins/loadSourcemaps/fixtures/input.ts
packages/ckeditor5-dev-build-tools/tests/plugins/loadSourcemaps/fixtures/tsconfig.json
packages/ckeditor5-dev-build-tools/tests/plugins/loadSourcemaps/loadSourcemaps.test.ts

Fix (build-tools): Fixed source maps generation for the UMD build. Fixes ckeditor/ckeditor5#16984.
Feature (build-tools): Introduced a new `loadSourcemaps` plugin for loading source maps of external dependencies.

Fix source maps generation for the UMD build.

---

CHANGELOG.md

Internal: Changelog for 43.0.0-alpha.0.
---

Changelog for 43.0.0-alpha.0

---

.eslintrc.js
packages/ckeditor5-dev-dependency-checker/bin/dependencychecker.js
packages/ckeditor5-dev-dependency-checker/lib/checkdependencies.js
packages/ckeditor5-dev-dependency-checker/lib/index.js
packages/ckeditor5-dev-dependency-checker/package.json

Internal (dependency-checker): Converted the package to ESM.
---

Migrated `ckeditor5-dev-dependency-checker` to ESM

---

.eslintrc.js
packages/ckeditor5-dev-bump-year/lib/bumpyear.js
packages/ckeditor5-dev-bump-year/lib/index.js
packages/ckeditor5-dev-bump-year/package.json

Internal (bump-year): Converted `ckeditor5-dev-bump-year` to ESM. 
Closes cksource/ckeditor5-internal#3763.
---

Converted `ckeditor5-dev-bump-year` to ESM.

---

DEPRECATIONS.md
packages/ckeditor5-dev-release-tools/lib/index.js
packages/ckeditor5-dev-release-tools/lib/tasks/verifypackagespublishedcorrectly.js
packages/ckeditor5-dev-release-tools/tests/index.js
packages/ckeditor5-dev-release-tools/tests/tasks/verifypackagespublishedcorrectly.js

Internal: Restored the `verifyPackagesPublishedCorrectly()` function and marked it deprecated.
---
* Part of https://github.com/ckeditor/ckeditor5-dev/pull/1019.

`verifyPackagesPublishedCorrectly()` is deprecated now

---

.circleci/template.yml
CHANGELOG.md
packages/ckeditor5-dev-release-tools/lib/tasks/creategithubrelease.js
packages/ckeditor5-dev-release-tools/lib/utils/assertnpmtag.js
packages/ckeditor5-dev-release-tools/lib/utils/getnpmtagfromversion.js
packages/ckeditor5-dev-release-tools/tests/tasks/creategithubrelease.js
packages/ckeditor5-dev-release-tools/tests/utils/assertnpmtag.js
packages/ckeditor5-dev-release-tools/tests/utils/getnpmtagfromversion.js
scripts/ci/is-project-ready-to-release.js

Changelog for v44.1.0 (as `next`).
---

Changelog for v44.1.0 (as next)

---

CHANGELOG.md
package.json
packages/ckeditor5-dev-release-tools/package.json

Fix (release-tools): Added a missing dependency (simple-git). Closes ckeditor/ckeditor5#17270.
Internal: Changelog for v44.1.1.
---

Added a missing dependency & changelog for v44.1.1.

---

CHANGELOG.md
package.json
packages/ckeditor5-dev-release-tools/lib/index.js
packages/ckeditor5-dev-release-tools/lib/utils/versions.js
packages/ckeditor5-dev-release-tools/tests/index.js
packages/ckeditor5-dev-release-tools/tests/utils/versions.js

Feature (release-tools): Created a new util exposed as `getNextInternal()` to generate an internal release version, e.g. `0.0.0-internal-20240102.0`.
Internal: Changelog for v44.2.0.
---

Util for generating an internal release version

---

packages/ckeditor5-dev-translations/lib/utils/createmissingpackagetranslations.js
packages/ckeditor5-dev-translations/lib/utils/getheaders.js
packages/ckeditor5-dev-translations/lib/utils/synchronizetranslationsbasedoncontext.js
packages/ckeditor5-dev-translations/tests/utils/createmissingpackagetranslations.js
packages/ckeditor5-dev-translations/tests/utils/getheaders.js
packages/ckeditor5-dev-translations/tests/utils/synchronizetranslationsbasedoncontext.js

Fix (translations): Align the number of plural forms to plural forms defined by a language in the `synchronizeTranslations()` function.
---
Closes cksource/ckeditor5-internal#3846

Synchronizing translations should take care of "Plural-Forms"

---

packages/ckeditor5-dev-release-tools/lib/tasks/commitandtag.js
packages/ckeditor5-dev-release-tools/tests/tasks/commitandtag.js

Other (release-tools): The `commitAndTag()` function understands a new parameter called `skipCi`. By default, release commits will not trigger a new workflow on CI. This behavior can be disabled when passing the `false` value.
---

Added skip ci to the `commitAndTag()` function.

---

packages/ckeditor5-dev-translations/lib/utils/addtranslation.js
packages/ckeditor5-dev-translations/lib/utils/synchronizetranslationsbasedoncontext.js
packages/ckeditor5-dev-translations/tests/utils/addtranslation.js
packages/ckeditor5-dev-translations/tests/utils/synchronizetranslationsbasedoncontext.js

Fix (translations): Fixed `synchronizeTranslations()` function to fill new translation entries for English in `en.po` with texts collected from the source code.
---
Closes cksource/ckeditor5-internal#3852.

The `synchronizeTranslations()` function does not fill "en.po"

---

CHANGELOG.md
packages/ckeditor5-dev-release-tools/lib/utils/publishpackageonnpmcallback.js
packages/ckeditor5-dev-release-tools/tests/utils/publishpackageonnpmcallback.js

Internal: Changelog for v45.0.2.
Internal: The `publishPackageOnNpmCallback()` util does not remove a package directory even if npm says it was published. Closes ckeditor/ckeditor5#17322.
---
I used _Internal_ messages as changelog contains the entry, so I would like to avoid duplications in the future releases.

Do not remove a package after publishing it "successfully"

---

CHANGELOG.md
packages/ckeditor5-dev-release-tools/lib/tasks/publishpackages.js
packages/ckeditor5-dev-release-tools/tests/tasks/publishpackages.js

Internal (release-tools): Increases the timeout value between the publishing packages phase and republishing the failed ones. Closes ckeditor/ckeditor5#17329.
Internal: Changelog for v45.0.4.
---
…hing packages phase and republishing the failed ones. Closes ckeditor/ckeditor5#17329.

Increased timeout for re-publishing packages

---

packages/ckeditor5-dev-release-tools/lib/tasks/publishpackages.js
packages/ckeditor5-dev-release-tools/lib/utils/checkversionavailability.js
packages/ckeditor5-dev-release-tools/lib/utils/executeinparallel.js
packages/ckeditor5-dev-release-tools/lib/utils/isversionpublishablefortag.js
packages/ckeditor5-dev-release-tools/lib/utils/publishpackageonnpmcallback.js
packages/ckeditor5-dev-release-tools/lib/utils/versions.js
packages/ckeditor5-dev-release-tools/tests/tasks/publishpackages.js
packages/ckeditor5-dev-release-tools/tests/utils/checkversionavailability.js
packages/ckeditor5-dev-release-tools/tests/utils/isversionpublishablefortag.js
packages/ckeditor5-dev-release-tools/tests/utils/publishpackageonnpmcallback.js
packages/ckeditor5-dev-release-tools/tests/utils/versions.js
packages/ckeditor5-dev-utils/lib/logger/index.js
packages/ckeditor5-dev-utils/tests/logger/index.js

Other (release-tools): Slow down the `npm publish` command due to weird errors on CI. Closes ckeditor/ckeditor5#17331.
Other (utils): Support for the `silent` logger mode.
---

Try to slow down the "npm publish" command

---

packages/ckeditor5-dev-release-tools/lib/tasks/publishpackages.js
packages/ckeditor5-dev-release-tools/lib/utils/checkversionavailability.js
packages/ckeditor5-dev-release-tools/lib/utils/isversionpublishablefortag.js
packages/ckeditor5-dev-release-tools/lib/utils/pacotecacheless.js
packages/ckeditor5-dev-release-tools/lib/utils/versions.js
packages/ckeditor5-dev-release-tools/tests/tasks/publishpackages.js
packages/ckeditor5-dev-release-tools/tests/utils/checkversionavailability.js
packages/ckeditor5-dev-release-tools/tests/utils/isversionpublishablefortag.js
packages/ckeditor5-dev-release-tools/tests/utils/pacotecacheless.js
packages/ckeditor5-dev-release-tools/tests/utils/versions.js

Fix (release-tools): The `publishPackages()` task should not throw an error after trying to publish packages after reaching an attempted limit. Instead, it should verify if the last try was successfully completed and throw the error if it wasn't. Closes ckeditor/ckeditor5#17333.
Other (release-tools): Increased the attempts limit from 3 to 5.
Other (release-tools): Created a decorated version of utils (`manifest()`, `packument()`) exposed by the `pacote` package. It prevents from using any cache when checking the npm registry. Direct calls have been replaced with the decorated version.
---

Improvements for the "publishPackages()" task

---

packages/ckeditor5-dev-release-tools/lib/utils/publishpackageonnpmcallback.js
packages/ckeditor5-dev-release-tools/tests/utils/publishpackageonnpmcallback.js

Other (release-tools): The `publishPackageOnNpmCallback()` util removes a package directory if npm says it was published. This reverts commit [`a1b37c7`](https://github.com/ckeditor/ckeditor5-dev/commit/a1b37c79347a7f74f88f6d945526e90b8ea96a67). Closes ckeditor/ckeditor5#17348.
---

Remove a package directory when npm says it was published

---

packages/ckeditor5-dev-translations/lib/movetranslations.js
packages/ckeditor5-dev-translations/lib/synchronizetranslations.js
packages/ckeditor5-dev-translations/lib/utils/getsourcemessages.js
packages/ckeditor5-dev-translations/lib/utils/isfileindirectory.js
packages/ckeditor5-dev-translations/tests/movetranslations.js
packages/ckeditor5-dev-translations/tests/synchronizetranslations.js
packages/ckeditor5-dev-translations/tests/utils/createmissingpackagetranslations.js
packages/ckeditor5-dev-translations/tests/utils/getpackagecontext.js
packages/ckeditor5-dev-translations/tests/utils/getpackagecontexts.js
packages/ckeditor5-dev-translations/tests/utils/getsourcemessages.js
packages/ckeditor5-dev-translations/tests/utils/isfileindirectory.js
packages/ckeditor5-dev-translations/tests/utils/movetranslationsbetweenpackages.js
packages/ckeditor5-dev-translations/tests/utils/synchronizetranslationsbasedoncontext.js

Fix (translations): Added support for providing `options.cwd` parameter to `synchronizeTranslations()` and `moveTranslations()` functions. This `options.cwd` (or `process.cwd()` if not set) is used to resolve paths to packages.
---
Closes cksource/ckeditor5-internal#3849.

Added support for providing `cwd` for translations scripts

---

.circleci/config.yml
packages/ckeditor5-dev-build-tools/package.json
packages/ckeditor5-dev-build-tools/src/config.ts
packages/ckeditor5-dev-utils/lib/styles/getpostcssconfig.js
packages/ckeditor5-dev-utils/package.json
packages/ckeditor5-dev-utils/tests/styles/getpostcssconfig.js
scripts/utils/parsearguments.js

Fix (utils): Upgrade the `postcss-nesting` package to the latest version to avoid issues with non-supported `@nest` selectors. Closes ckeditor/ckeditor5#17449.
Internal (build-tools): Upgrade `postcss-nesting` to the latest version.
---

Upgrade postcss-nesting to latest version

---

packages/ckeditor5-dev-release-tools/lib/utils/executeinparallel.js
packages/ckeditor5-dev-release-tools/tests/utils/executeinparallel.js

Fix (release-tools): Fixed path calculation in `executeInParallel()` util that prepares a path to a dynamically imported worker script. Previously, it did not work in Windows, because there is a specific requirement that absolute path must be valid `file://` protocol URL. Now, the worker script is always imported using `file://` protocol URL.
---
Closes cksource/ckeditor5-internal#3882.
I'm not using `url.pathToFileURL()` to convert the path to a `file://` protocol URL, because it produces unexpected results in tests where we mock `process.cwd()` to be Windows-style.
Example: when mocked `process.cwd()` is `C:\Users\ckeditor`, then `url.pathToFileURL( 'C:/Users/ckeditor/uuid-4.mjs' )` internally tries to create an URL from `file://C:%5CUsers%5Cckeditor/C:/Users/ckeditor/uuid-4.mjs` and …

Pass path to a dynamically imported file as `file://` protocol URL to make it work in Windows

---

.eslintrc.cjs
packages/ckeditor5-dev-build-tools/package.json
packages/ckeditor5-dev-build-tools/tests/build/fixtures/src/input.ts

Tests (build-tools): Improved a JSON import to make it compatible with TypeScript 5.7. Closes ckeditor/ckeditor5#17526.
---

Improved a JSON import to make it compatible with TypeScript 5.7

---

scripts/publishpackages.js

Internal: Updated the `release_id` property to point to the `v43.0.1` tag.
---

Mark v43.0.1 as the `@latest` release

---

package.json
packages/ckeditor5-dev-dependency-checker/lib/checkdependencies.js

Internal: Update `eslint-config-ckeditor5` to `^9.0.0`.
Feature (dependency-checker): Treat type dependencies as production dependencies. Related to ckeditor/ckeditor5#17213.
MINOR BREAKING CHANGE (dependency-checker): Treat type dependencies as production dependencies.

Treat type dependencies as production dependencies

---

packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js

Fix (tests): Disable tree-shaking in webpack. See ckeditor/ckeditor5#17767.

Disable tree-shaking in tests

---

packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-tests/tests/tasks/runautomatedtests.js

Internal: Fixed automated tests entry point on Windows. Closes ckeditor/ckeditor5#17797.
---

Fixed automated tests entry point on Windows.

---

packages/ckeditor5-dev-build-tools/tests/_utils/utils.ts

Internal: Update target in `build-tools` tests to `es2022`.
---
This should be set to `es2022` from the beginning.

Internal: Update target in `build-tools` tests to `es2022`.

---

packages/ckeditor5-dev-release-tools/lib/index.js
packages/ckeditor5-dev-release-tools/lib/utils/versions.js
packages/ckeditor5-dev-release-tools/tests/index.js
packages/ckeditor5-dev-release-tools/tests/utils/versions.js

Other (release-tools): Exported the `getDateIdentifier()` util that converts the current date into `YYYYMMDD` format.
Other (release-tools): Improved the `getLastPreRelease()` util to distinguish pre-release versions starting with the same base name. Previously, `getLastPreRelease( '0.0.0-nightly' )` matched both `0.0.0-nightly` and `0.0.0-nightly-next` versions, but now only the first one is matched.
---

Improved calculating pre-release versions that start with the same base name

---

packages/ckeditor5-dev-release-tools/lib/utils/getnpmtagfromversion.js
packages/ckeditor5-dev-release-tools/tests/utils/getnpmtagfromversion.js

Fix (release-tools): Fixed calculating npm tag for the `nightly-next` pre-release version. Closes ckeditor/ckeditor5#17904.
---

Fixed calculating npm tag for the `nightly-next` pre-release version

---

packages/ckeditor5-dev-web-crawler/lib/constants.js
packages/ckeditor5-dev-web-crawler/lib/runcrawler.js

Fix (web-crawler): Ignore false positive `net::ERR_ABORTED` error reported when POST request responds with 204 HTTP status code. Closes ckeditor/ckeditor5#17969.
---

Ignore false positive ERR_ABORTED for 204 responses in requestfailed logging

---

packages/ckeditor5-dev-build-tools/src/build.ts
packages/ckeditor5-dev-build-tools/src/utils.ts
packages/ckeditor5-dev-build-tools/tests/build/arguments.test.ts
packages/ckeditor5-dev-build-tools/tests/build/build.test.ts
packages/ckeditor5-dev-build-tools/tests/config/config.test.ts
packages/ckeditor5-dev-build-tools/tests/utils.test.ts

Other (build-tools): Added support for providing custom current working directory.
Other (build-tools): Do not start generating UMD build if both `browser` and `name` parameters are missing, because both are required.
---

Added support for providing custom current working directory

---

CHANGELOG.md
packages/ckeditor5-dev-release-tools/lib/tasks/commitandtag.js
packages/ckeditor5-dev-release-tools/tests/tasks/commitandtag.js

Internal: The `commitAndTag()` function now uses annotated tags instead of lightweight ones to allow signing tags while preparing a release. Closes ckeditor/ckeditor5#18080.
---

Added annotation to the tag created during a release process to fix the release process.

---

packages/ckeditor5-dev-build-tools/src/plugins/replace.ts

Internal (build-tools): Fixed types mismatch between different `@types/estree` versions. Closes ckeditor/ckeditor5#18220.
---

Fixed types mismatch between different `@types/estree` versions

---

packages/ckeditor5-dev-build-tools/src/config.ts
packages/ckeditor5-dev-build-tools/src/index.ts
packages/ckeditor5-dev-build-tools/src/plugins/loadSources.ts
packages/ckeditor5-dev-build-tools/tests/config/config.test.ts
packages/ckeditor5-dev-build-tools/tests/plugins/loadSources/fixtures/input.ts
packages/ckeditor5-dev-build-tools/tests/plugins/loadSources/fixtures/source.js
packages/ckeditor5-dev-build-tools/tests/plugins/loadSources/fixtures/source.ts
packages/ckeditor5-dev-build-tools/tests/plugins/loadSources/fixtures/tsconfig.json
packages/ckeditor5-dev-build-tools/tests/plugins/loadSources/loadSources.test.ts

Fix (build-tools): Prioritize `.ts` over `.js` files.
---
This PR causes the `.ts` file to take precedence if both `.js` and `.ts` files are present on the file system. This prevents potentially old and obsolete build files from overriding current source files.
It also reverts the changes made in #1051 so that the TypeScript plugin is only used if the `declaration: true` option is passed. This improves the build time of:
* `ckeditor5-premium-features` by ~24s (from 65.5s down to 41.5s),
* documentation (`yarn docs --skip-validation --skip-api`) by ~20s (from 111s down to 89.5s).

Fix (build-tools): Prioritize `.ts` over `.js` files

---

packages/ckeditor5-dev-web-crawler/package.json
packages/ckeditor5-dev-web-crawler/src/constants.ts
packages/ckeditor5-dev-web-crawler/src/getlinks.ts
packages/ckeditor5-dev-web-crawler/src/runcrawler.ts

Internal (web-crawler): Increase the number of concurrent workers to equal the number of CPU threads, but no more than 16.
Internal (web-crawler): Properly read console errors.
Feature (web-crawler): Improve performance.
MINOR BREAKING CHANGE (web-crawler): Rename `noSpinner` to `silent`.
---
While the old implementation took about **45 to 50 minutes** to validate all uber docs, the new one does it in **less than 4 minutes** on my laptop.
```text
== Start:     2025-04-15 09:39:05.055
== Now:       2025-04-15 09:42:52.254 (running for 3.8 minutes)
== Progress:  3828 / 3828 (100.00%), errors: 0 (0.00%)
== Remaining: 0.0 ms (@ 16.85 pages/second)
== Sys. load: 92.1% CPU / 41.8% memory
== Workers:   16
```
Here's the breakdown of the changes and how they reduced the build time:
1. Base: **50 …

Feature (web-crawler): Improve performance.

---

.gitignore
scripts/postinstall.js

Internal: Improved the `postinstall` hook. Right now, the script searches for packages to build automatically. When converting packages to TypeScript, it is no longer necessary to add a new package manually.
---

Improved the `postinstall` hook

---

packages/ckeditor5-dev-web-crawler/src/runcrawler.ts

Internal: Properly handle and filter `UNCAUGHT_EXCEPTION` errors.
---
Errors detected on the page should be added to `pageErrors` array first, so they can be filtered out before being added to the root `errors` map. See changes made in #1108.

Internal: Properly handle and filter `UNCAUGHT_EXCEPTION` errors.

---

packages/ckeditor5-dev-dependency-checker/lib/checkdependencies.js
packages/ckeditor5-dev-dependency-checker/package.json

Feature (dependency-checker): Treat paths used in `import.meta.resolve` as potential dependencies.
Feature (dependency-checker): Improve performance.
---
**Using `oxc-parser` improves the performance by about 30%.**

Feature (dependency-checker): Treat paths used in `import.meta.resolve` as potential dependencies.

---

packages/ckeditor5-dev-docs/lib/build.js
packages/ckeditor5-dev-docs/tests/build.js
packages/typedoc-plugins/src/index.ts
packages/typedoc-plugins/src/restore-program-after-conversion/index.ts
packages/typedoc-plugins/tests/event-inheritance-fixer/index.ts
packages/typedoc-plugins/tests/event-param-fixer/index.ts
packages/typedoc-plugins/tests/interface-augmentation-fixer/index.ts
packages/typedoc-plugins/tests/module-fixer/index.ts
packages/typedoc-plugins/tests/purge-private-api-docs/index.ts
packages/typedoc-plugins/tests/restore-program-after-conversion/fixtures/foo.ts
packages/typedoc-plugins/tests/restore-program-after-conversion/fixtures/tsconfig.json
packages/typedoc-plugins/tests/restore-program-after-conversion/index.ts
packages/typedoc-plugins/tests/symbol-fixer/index.ts
packages/typedoc-plugins/tests/tag-error/fixtures/customerror.ts
packages/typedoc-plugins/tests/tag-error/index.ts
packages/typedoc-plugins/tests/tag-event/index.ts
packages/typedoc-plugins/tests/tag-observable/index.ts
packages/typedoc-plugins/tests/validators/fires-validator/index.ts
packages/typedoc-plugins/tests/validators/link-validator/index.ts
packages/typedoc-plugins/tests/validators/module-validator/index.ts
packages/typedoc-plugins/tests/validators/overloads-validator/index.ts
packages/typedoc-plugins/tests/validators/see-validator/index.ts

Internal: Added support for `typedoc@0.28.3`, which requires that access to _TypeScript program_ takes place only during source files conversion and not later. Closes ckeditor/ckeditor5#18414.
---
1. Setup: `ckeditor5`, `ckeditor5-dev` and `umberto` on `#ck/epic/15619-typedoc-28` branch. Reinstall dependencies to make sure `typedoc@0.28.3` is installed.
2. First, ensure that `yarn run docs` crashes:
```
Error: Process exited with code 1
at ChildProcess.<anonymous> (file:///D:/Projects/ckeditor/ckeditor5/scripts/docs/build-docs.mjs:107:13)
at ChildProcess.emit (node:events:518:28)
at maybeClose (node:internal/child_process:1104:16)
at ChildProcess._handle.onexit (node:internal/child_process:304:5)
```
4. Then, switch `ckeditor5-dev` to `#ck/18414` branch and run `yarn run docs` again. The …

Restore TypeScript program after converting the sources

---

packages/ckeditor5-dev-web-crawler/src/constants.ts
packages/ckeditor5-dev-web-crawler/src/runcrawler.ts

Feature (web-crawler): Block requests from `IGNORED_HOSTS`.
---
See ckeditor/ckeditor5#18426.
I removed `ucarecdn.com` and `svc.webspellchecker.net` from `IGNORED_HOSTS`, because resources from these hosts are used in the editors. While `ucarecdn.com` can be re-added if it later causes issues for us, the `svc.webspellchecker.net` is required for the editor to function properly.
---
To test this PR, run the `yarn run docs --dev --skip-validation` command.
Then, run the following commands few times:
- `bash scripts/check-manual-tests.sh -r ckeditor5 -f ckeditor5`
- `bash external/ckeditor5-commercial/scripts/ci/check-documentation.sh`
No runs should fail due to timeout or failed request/response from external hosts.
To confirm, you can also run these two commands on current `master` branch. …

Feature (web-crawler): Block requests from `IGNORED_HOSTS`.

---

packages/ckeditor5-dev-release-tools/lib/tasks/commitandtag.js
packages/ckeditor5-dev-release-tools/tests/tasks/commitandtag.js

Fix (release-tools): Fixed `commitAndTag()` throwing an `ENAMETOOLONG` error when trying to commit a large number of files on Windows.
---

Fixed commits exceeding character limit

---

packages/ckeditor5-dev-changelog/src/utils/getsectionswithentries.ts
packages/ckeditor5-dev-changelog/tests/utils/getsectionswithentries.test.ts

Feature: Enabled links to a different repositories. Closes ckeditor/ckeditor5#18323.
---

Enabled links to a different repositories

---

packages/ckeditor5-dev-changelog/src/generatechangelog.ts
packages/ckeditor5-dev-changelog/src/types.ts
packages/ckeditor5-dev-changelog/src/utils/getnewversion.ts
packages/ckeditor5-dev-changelog/src/utils/getsectionswithentries.ts
packages/ckeditor5-dev-changelog/tests/generatechangelog.test.ts
packages/ckeditor5-dev-changelog/tests/utils/getnewversion.test.ts
packages/ckeditor5-dev-changelog/tests/utils/getsectionswithentries.test.ts

Feature: Added `returnChangelog` option for the `generateChangelog()` function that makes the function return the changelog instead of writing it to a file. Closes ckeditor/ckeditor5#18064.
---
The option also prevents changesets from deletion, and handles version automatically instead of asking the user to pick one.

Enabled returning changelog instead of writing it

---

packages/ckeditor5-dev-docs/lib/build.js

Fix (docs): Fixed rendering values of the `@default` tag in API docs. Previously, TypeDoc tried to guess whether the `@default` tag value should be treated as a code, which produced invalid outputs in some cases. Now it just takes the value from this tag and renders it as inline code. Closes ckeditor/ckeditor5#18526.
---
I checked a few `@default` tags and it seems they are now rendered correctly:

Fix rendering values of the `@default` tag in API docs

---

packages/ckeditor5-dev-changelog/src/types.ts
packages/ckeditor5-dev-changelog/src/utils/generatechangelog.ts
packages/ckeditor5-dev-changelog/src/utils/groupentriesbysection.ts
packages/ckeditor5-dev-changelog/src/utils/parsechangelogentries.ts
packages/ckeditor5-dev-changelog/src/utils/sortentriesbyscopeanddate.ts
packages/ckeditor5-dev-changelog/tests/utils/generatechangelog.ts
packages/ckeditor5-dev-changelog/tests/utils/groupentriesbysection.ts
packages/ckeditor5-dev-changelog/tests/utils/normalizeentry.ts
packages/ckeditor5-dev-changelog/tests/utils/parsechangelogentries.ts
packages/ckeditor5-dev-changelog/tests/utils/sortentriesbyscopeanddate.ts
packages/ckeditor5-dev-changelog/tests/utils/validateentry.ts

Internal: Added sorting entries by date and scope count. Closes ckeditor/ckeditor5#18534.
---

Added sorting entries by date and scope count

---

.changelog/20250611114035_ck_18665_fix_changelog_generation.md
packages/ckeditor5-dev-changelog/package.json

The template file for the changelog entries generator is included in the published package to avoid issues when using the `ckeditor5-dev-changelog-create-entry` binary script.
---
* Closes ckeditor/ckeditor5#18665.

Fix changelog entry generation

---

.changelog/20250625125147_ck_18745_add_support_for_raw_query_params_master.md
packages/ckeditor5-dev-build-tools/src/config.ts
packages/ckeditor5-dev-build-tools/src/index.ts
packages/ckeditor5-dev-build-tools/src/plugins/rawImport.ts
packages/ckeditor5-dev-build-tools/tests/plugins/rawImport/fixtures/dependency.css
packages/ckeditor5-dev-build-tools/tests/plugins/rawImport/fixtures/dependency.js
packages/ckeditor5-dev-build-tools/tests/plugins/rawImport/fixtures/dependency.txt
packages/ckeditor5-dev-build-tools/tests/plugins/rawImport/fixtures/input.js
packages/ckeditor5-dev-build-tools/tests/plugins/rawImport/rawImport.test.ts

Add support for importing raw file content by appending `?raw` query parameter to the import path.
---
See https://github.com/ckeditor/ckeditor5/issues/18745

Add support for importing raw file content by appending `?raw` query parameter to the import path.

---

.changelog/20250627134956_commercial_7977_expose_timeout_option.md
packages/ckeditor5-dev-web-crawler/src/index.ts
packages/ckeditor5-dev-web-crawler/src/runcrawler.ts

Add the `timeout` configuration option to the `runCrawler` function and export the `DEFAULT_TIMEOUT` variable.
---
I'm testing whether we can use Docker executors instead of Machine executors in CircleCI, but I get timeouts on one of the heavy manual tests focused on testing performance. Currently, there is no way to override the default 15s timeout.

Add the `timeout` configuration option to the `runCrawler` function

---

.changelog/20250702151707_ck_18772_bc_major.md
packages/ckeditor5-dev-changelog/src/utils/determinenextversion.ts
packages/ckeditor5-dev-changelog/tests/utils/determinenextversion.ts

This PR improves the detection of an upcoming release version when processing a "Breaking change" entry within a single repository.
---
* Closes https://github.com/ckeditor/ckeditor5/issues/18772.
---
**I checked it on Umberto:**
It works the same if an entry is specified as a major or minor breaking change.
**A mono-repo is not affected:**
* Type: `breaking change`
* Type `minor bc`
* Type `major bc`

Bump a major version when processing a single repo and BREAKING CHANGE

---

.changelog/20250813102923_internal_4083.md
packages/ckeditor5-dev-tests/bin/testautomated.js
packages/ckeditor5-dev-tests/bin/testmanual.js

Don't hardcode the path to the `@ckeditor/ckeditor5-theme-lark` package.
---
* See https://github.com/ckeditor/ckeditor5-internal/issues/4083.

Don't hardcode the path to the `@ckeditor/ckeditor5-theme-lark` package.

---

.changelog/20250805131318_ck_18905.md
packages/ckeditor5-dev-docs/package.json
packages/typedoc-plugins/package.json

Bumped TypeDoc to the latest version v0.28.9.
---
* This PR requires https://github.com/ckeditor/ckeditor5/pull/18941.
* Closes ckeditor/ckeditor5#18905.
---
1. The differences between the generated `output.json` in TypeDoc v0.28.5 and v0.28.9 shows that v0.28.9 adds more data (~150 KB). The changes are mostly related to:
- changed order of IDs,
- added `implementationOf` details for `Iterable.[iterator]`:
```diff
"implementationOf": {
"type": "reference",
-   "target": -1,
-   "name": "Iterable.[iterator]"
+   "target": {
+       "packageName": "typescript",
+       "packagePath": "lib/lib.es2015.iterable.d.ts",
+       "qualifiedName": "Iterable.[iterator]"
+   },
+   "name": "Iterable.[iterator]",
+   "package": "typescript"
}
```
- added more metadata:
```diff
"overwrites": {
"type": …
```

Bumped TypeDoc to the latest version v0.28.9

---

.changelog/20250813120310_ck_18936.md
packages/ckeditor5-dev-changelog/src/tasks/generatechangelogformonorepository.ts
packages/ckeditor5-dev-changelog/src/tasks/generatechangelogforsinglerepository.ts
packages/ckeditor5-dev-changelog/src/types.ts
packages/ckeditor5-dev-changelog/src/utils/findchangelogentrypaths.ts
packages/ckeditor5-dev-changelog/src/utils/generatechangelog.ts
packages/ckeditor5-dev-changelog/src/utils/groupentriesbysection.ts
packages/ckeditor5-dev-changelog/src/utils/parsechangelogentries.ts
packages/ckeditor5-dev-changelog/tests/tasks/generatechangelogformonorepository.ts
packages/ckeditor5-dev-changelog/tests/tasks/generatechangelogforsinglerepository.ts
packages/ckeditor5-dev-changelog/tests/utils/findchangelogentrypaths.ts
packages/ckeditor5-dev-changelog/tests/utils/generatechangelog.ts
packages/ckeditor5-dev-changelog/tests/utils/groupentriesbysection.ts
packages/ckeditor5-dev-changelog/tests/utils/movechangelogentryfiles.ts
packages/ckeditor5-dev-changelog/tests/utils/normalizeentry.ts
packages/ckeditor5-dev-changelog/tests/utils/parsechangelogentries.ts
packages/ckeditor5-dev-changelog/tests/utils/removechangelogentryfiles.ts
packages/ckeditor5-dev-changelog/tests/utils/sortentriesbyscopeanddate.ts
packages/ckeditor5-dev-changelog/tests/utils/validateentry.ts

Added a top-level `linkFilter()` callback option for changelog generators that determines which issue links should be preserved in the generated changelog and which should be removed. If the `shouldSkipLinks` flag is also provided, the `shouldSkipLinks` flag takes precedence over the `linkFilter()` callback to maintain backward compatibility.
---
* Closes https://github.com/ckeditor/ckeditor5/issues/18936.
---
When this PR is released, we can merge https://github.com/ckeditor/ckeditor5/pull/18964.
1. Switch to `ck/18936` branch in `ckeditor5-dev` repository. We are going to check if link to `ckeditor/ckeditor5#18936` is **skipped** or **preserved** in the changelog output.
2. Execute `yarn release:prepare-changelog --dry-run`.
- Expected result: link is **preserved**.
3. Update …

[dev-changelog] Top-level `linkFilter()` callback

---

.changelog/20250904161709_ck_19064_add_kapa_ai_to_ignored_hosts.md
packages/ckeditor5-dev-web-crawler/src/constants.ts

Add `kapa.ai` to the list of ignored hosts.
---
* Closes https://github.com/ckeditor/ckeditor5/issues/19064
---
The original issue is about blocking `csp.withgoogle.com`, as this was the domain shown by the crawler. However, the actual root cause is code being downloaded from `kapa.ai`.
Blocking requests to this domain reduces the crawl time for all ~4,000 pages from 9.5 minutes back to 5.1 minutes.

Add `kapa.ai` to the list of ignored hosts.

---

.changelog/20250909144153_core_19082_increase_timeout_in_web_crawler_to_30_s.md
packages/ckeditor5-dev-web-crawler/src/constants.ts

Increase timeout in `ckeditor5-dev-web-crawler` from 15 to 30 seconds.
---
* Closes https://github.com/ckeditor/ckeditor5/issues/19082
---
N/A

Increase timeout in `ckeditor5-dev-web-crawler` from 15 to 30 seconds.

---

.changelog/20251003145641_cc_8556_use_workspace_as_version.md
packages/ckeditor5-dev-changelog/package.json
packages/ckeditor5-dev-dependency-checker/lib/checkversionmatch.js
packages/ckeditor5-dev-dependency-checker/package.json
packages/ckeditor5-dev-dependency-checker/tests/checkversionmatch.js
packages/ckeditor5-dev-docs/package.json
packages/ckeditor5-dev-release-tools/package.json
packages/ckeditor5-dev-stale-bot/package.json
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-translations/package.json
packages/ckeditor5-dev-utils/package.json
pnpm-lock.yaml
scripts/ci/check-dependencies-versions-match.mjs
scripts/preparepackages.js

Updated the `checkVersionMatch()` function to support the [`workspace:*`](https://pnpm.io/workspaces) protocol for dependencies.
Added a `workspacePackages` option that specify the list of packages that should use `workspace:*` instead of specific version numbers. Both `dependencies` and `devDependencies` are validated to ensure consistent workspace versioning with pnpm.
Switched to using `workspace:*` in monorepo workspace, so that the lock file is not broken after a release.
---
* See ckeditor/ckeditor5-commercial#8556
---
*Optional: Notes on decisions, edge cases, or anything helpful for reviewers.*

Using `workspace:*` for dependencies in `checkVersionMatch` function.
